### ISSUE TITLE
Does it support multiple thread or process in C++?  

### ISSUE THREAD

**Issue by wjtan99** [nmslib/hnswlib#100]
Does it support multiple thread or process in C++?  
If yes, do you have an example?  
Thanks a lot.

**Comment by yurymalkov** [comment]
@wjtan99 
The search method is thread-safe and insertion method is thread-safe (with an exclusion of the first element). So you can do batch-parallel insertions and searches. 
The example is https://github.com/nmslib/hnswlib/blob/master/sift_1b.cpp, you can uncomment all omp pragmas to make the searches parallel.

Note that searching and inserting are not thread-safe between each other (e.g. no searching and inserting the elements at the same time).

**Comment by wjtan99** [comment]
@yurymalkov Thanks a lot for your quick response. That is very helpful.

**Comment by wjtan99** [comment]
@yurymalkov I see that insertion is very simple to call addPoint.  Can this operation done on-the-fly, meaning that new elements being added as needed. I am not taking about inserting and searching at same time.  I am talking about if all k returned results are invalid (e.g., cosine distance is too small), then we add the target into the data set corpus. 
Thanks again.
