### ISSUE TITLE
Can you suggest ef and M for 512 dimentional float data search  

### ISSUE THREAD

**Issue by wjtan99** [nmslib/hnswlib#103]
Hi, Thanks a lot for your great great work.  

I tested in on a 512-dimensinal float data.  I used the same ef_construction=40, M = 16 as in the sift1b test. But the query time is longer when ef = 10 than ef is larger.  I have 19K data, and do about 700 query,  the average search time for ef=10 is 15ms, while it is 3~4 ms for ef>30.    

Can you suggest a good set of parameters at the construction and at the query time?

**Comment by wjtan99** [comment]
I found bug in my code.  After fixing the bug, the search time gets longer when ef gets larger.  But still, can you suggest parameters for my case?  
Thanks a lot.

**Comment by yurymalkov** [comment]
Hi @wjtan99. A proper way to infer the parameters is to cross validation with accuracy measurements. I.e. the optimal parameters depend on your target accuracy. `efConstruction` should large enough so that a searcf with `ef` on the resulting dataset would give >0.9 recall.

**Comment by wjtan99** [comment]
Thanks.
