### ISSUE TITLE
saved index is not cross platform?

### ISSUE THREAD

**Issue by HaoLiuHust** [nmslib/hnswlib#108]
I have saved an index file on linux, and I want to load it on arm, but it can not be done, old index error occured. Is it by design?

**Comment by HaoLiuHust** [comment]
@yurymalkov

**Comment by HaoLiuHust** [comment]
I have figure out the problem, because of sizeof(size_t) is 8 on linux, 4 on arm. change it to uint32 can solve this problem

**Comment by searchivarius** [comment]
@HaoLiuHust only if your ARM is little endian (as Intel).

**Comment by WellWang-S** [comment]
> I have figure out the problem, because of sizeof(size_t) is 8 on linux, 4 on arm. change it to uint32 can solve this problem

Where to set the data type
