### ISSUE TITLE
Search stop by threshold

### ISSUE THREAD

**Issue by UpCoder** [nmslib/hnswlib#109]
Hi,
   I try to use hnswlib to retrieval the image. 
  In search stage, how can I get all images whose similarity is higher than some threshold?  I just know use the knn_query(), which need us to point the K.

Thank you!

**Comment by yurymalkov** [comment]
Hi @UpCoder,
This is a different functionality not available at the moment. Some coding in c++ can add it.

**Comment by UpCoder** [comment]
OK, Thanks. ^_^
