### ISSUE TITLE
How much effort to implement post=2 option?

### ISSUE THREAD

**Issue by connellybarnes** [nmslib/hnswlib#110]
For nmslib there is an option post=2, which was also previously discussed in nmslib [1].

I wonder how much effort it would be (estimated) in terms of days or lines of code to port that into hnswlib? Also, would hnswlib be interested to accept a pull request for that?

Thanks, Connelly

[1]. https://github.com/nmslib/nmslib/issues/121

**Comment by yurymalkov** [comment]
As discussed via emails, the effort depends on how good a person can navigate the hnswlib code. If he/she is familiar with the code and the principle, I think it would take a day or two.
If not familiar with the code, I think it would take up to a week.
