### ISSUE TITLE
Trouble Reading Your Code

### ISSUE THREAD

**Issue by wslfs** [nmslib/hnswlib#112]
![image](https://user-images.githubusercontent.com/18738958/59436370-11ca1780-8e22-11e9-9e2a-611b3372ede1.png)

In your code here, you want to replace one of the idx's neighbor with cur_c. In previous code, you
already add idx to cur_c's neighbor, but here cur_c  may not be choosen as a neighbor of idx, in this case, you create a single direction edge from cur_c to idx? Am i right?

**Comment by yurymalkov** [comment]
Hi @wslfs,
In the preferred code https://github.com/nmslib/hnswlib/blob/d0716d9962ec4ba100a5de551f07c2067e835785/hnswlib/hnswalg.h#L416-L437 `idx` is the relative index of `cur_c`'s neighbor (`cur_c` is the index of the element that is being added), `j` is the relative index of `idx`-element neighbors. What it does it creates a list of all neighbors of `idx`, adds `cur_c` to the list and filters the list by using a heuristic. The list is then is set as new neighbors of `idx`.

In the previous code https://github.com/nmslib/hnswlib/blob/d0716d9962ec4ba100a5de551f07c2067e835785/hnswlib/hnswalg.h#L368-L389 the element `cur_c` gets creates a connection to `idx`, but not the other way. You may be referring to https://github.com/nmslib/hnswlib/blob/d0716d9962ec4ba100a5de551f07c2067e835785/hnswlib/hnswalg.h#L412-L415, but this line is a different if-brach from the code you reference.

Hope it helps.

**Comment by wslfs** [comment]
Thank you.  So is it possible that cur_c will be filtered and idx will not add it as a neighbor?

**Comment by yurymalkov** [comment]
Yes, this might happen.

**Comment by wslfs** [comment]
Thank you，however in this case ，cur_c still keeps idx as its neighbor, you get a directed graph. Is this ok?

**Comment by yurymalkov** [comment]
This might create problems if some elements have low inbound connections (making them hard to reach), leading to some performance loss at the exchange of simplicity of incremental construction.

**Comment by wslfs** [comment]
Thank you for all your reply. I am implementing hnsw my self，you help me understand the algorithm better.
