### ISSUE TITLE
Core dumped when running sift_test1B

### ISSUE THREAD

**Issue by uestc-lfs** [nmslib/hnswlib#118]
I use the newest code from master branch and I follow the instructions in readme, that is:

`
cmake . && make all && ./main
`

The result is 

`
Loading GT:
Loading queries:
Building index:
terminate called after throwing an instance of 'std::runtime_error'
  what():  The newly inserted element should have blank link list
[1]    28599 abort (core dumped)  ./main
`

The backtrace is as follows:

`
(gdb) bt
#0  0x00007ffff6fc7428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6fc902a in __GI_abort () at abort.c:89
#2  0x00007ffff7b32b39 in __gnu_cxx::__verbose_terminate_handler ()
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7b311fb in __cxxabiv1::__terminate (handler=<optimized out>)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff7b31234 in std::terminate ()
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff7b31416 in __cxxabiv1::__cxa_throw (obj=0x7fefb4000fe0, 
    tinfo=0x7ffff7dc8eb0 <typeinfo for std::runtime_error>, 
    dest=0x7ffff7b3cc86 <std::runtime_error::~runtime_error()>)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x000000000040b8ea in hnswlib::HierarchicalNSW<int>::mutuallyConnectNewElement(void*, unsigned int, std::priority_queue<std::pair<int, unsigned int>, std::vector<std::pair<int, unsigned int>, std::allocator<std::pair<int, unsigned int> > >, hnswlib::HierarchicalNSW<int>::CompareByFirst>, int) ()
#7  0x000000000040c8f3 in hnswlib::HierarchicalNSW<int>::addPoint(void*, unsigned long, int) ()
---Type <return> to continue, or q <return> to quit---
#8  0x00000000004052fa in sift_test1B() [clone ._omp_fn.0] ()
#9  0x00007ffff758143e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#10 0x00007ffff6b786ba in start_thread (arg=0x7ff0f249f700)
    at pthread_create.c:333
#11 0x00007ffff709941d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

This is where exception was throwed:
https://github.com/nmslib/hnswlib/blob/68c5531caa8be522b19ac20088ffca39d1474520/hnswlib/hnswalg.h#L389-L396

I have not change any code, I guess that some thread has write to the wrong address that makes `*ll_cur` non zero.

**Comment by yurymalkov** [comment]
Hi @wslfs,
Thank you! I'll check it. 
Some updates probably broke it... Probably, will add a test to Travis.

**Comment by yurymalkov** [comment]
It seems that this is a multi-threaded issue introduced with #105.
Will look more closely into it.

**Comment by bjmiao** [comment]
A naive way is to modify the OpenMP thread number:
- [ export OMP_NUM_THREADS=1 ]
which works for me.

**Comment by yurymalkov** [comment]
I've upload a fix for this issue tomorrow after some checks. 
The fix should also nullify the the overhead introduced by support of deletions.

**Comment by uestc-lfs** [comment]
nice jobs! @yurymalkov
