### ISSUE TITLE
Core dumped when using bruteforce

### ISSUE THREAD

**Issue by jshang2** [nmslib/hnswlib#126]
It seems the same problem of this issue:
nmslib/hnswlib#118

It occurs when adding points and shows some runtime error.

**Comment by yurymalkov** [comment]
@jshang2 Thanks! I'll look into it soon.
Can you please also provide a code to reproduce it? That would be very helpful.

**Comment by jshang2** [comment]
Hi, I've just replace the HierarchicalNSW to BruteforceSearch and add some minor change in sift_1b.cpp file. Here's the code.
[sift_1b.txt](https://github.com/nmslib/hnswlib/files/3423409/sift_1b.txt)

**Comment by yurymalkov** [comment]
@jshang2 Thanks! I'll check it when get back from traveling.

**Comment by yurymalkov** [comment]
Hi @jshang2,
Should be fixed right now.

**Comment by jshang2** [comment]
Great! Thank you very much.
