### ISSUE TITLE
Unreasonable memory consumption

### ISSUE THREAD

**Issue by siminchengithub** [nmslib/hnswlib#141]
I  am adding  2M 800-d dense vectors to a l2 space with integer labels, M is set to 64. While building the index, the memory consumption goes up to 35G. However 2M*(800*8+64*8-10) = 14G.

What am I doing wrong here?
`self.p = hnswlib.Index(space = self.space, dim = dim)

 self.p.init_index(max_elements = size, ef_construction = self.ef_construction, M = self.M)

 self.p.add_items(vectors, range(size))

 self.p.set_ef(self.M) # ef should always be > k`

**Comment by yurymalkov** [comment]
Hi @siminchengithub ,
I am not sure what is the problem, but it seems there is some kind of data duplication. 

There is an additional overhead for the memory compared to the equation, but your memory consumption is clearly unreasonable.

Few questions:
1. What is the dtype of the vectors? 
2. Is it a contiguous array (this might lead to an additional data copy)?
3. How did you measure the memory consumption of the index? Memory before and after creation of the index?

Also, note that the index stores the copy of all data inside it to compute the distances, and the default type is float (e.g. 4 bytes per vector dimension - this seems to be in line with your calculations).
