### ISSUE TITLE
How to install v0.2

### ISSUE THREAD

**Issue by UpCoder** [nmslib/hnswlib#145]
Hi, I used this command to install hnswlib
```bash 
pip install --user git+https://github.com/nmslib/hnswlib#subdirectory=python_bindings
```
it is v0.2

but now it is v0.3, So how can I install v0.2?

Thank you!

**Comment by yurymalkov** [comment]
Hi @UpCoder ,
I've added a tag for v0.2, so you should be able to use the following command:
```bash
pip3 install --user git+https://github.com/nmslib/hnswlib.git@v0.2#subdirectory=python_bindings
```

I wonder, are experiencing problems with the current version in master (it should be backward compatible with v0.2)?

**Comment by UpCoder** [comment]
Thank you for your reply. But I found it can not solve my problem.
When I load the index file which I trained on v0.2 instead of v0.3, it will occur this error:
```
Warning: Calling load_index for an already inited index. Old index is being deallocated.Warning: loading of old indexes will be deprecated before 2019.
Please resave the index in the new format.
File "/opt/tiger/ensemble_work/projects/RetrievalVideoWeb/back_end/retrieval/retrieval_douyin.py", line 38, in build_hnsw
    p.load_index(index_save_path, max_elements=paras['construct']['num_elements'])
MemoryError: std::bad_alloc
```

But I change the version to 0.2, It still doesn't work for me. 

Do you have any suggestion about that?

The memory is enough:
```
top - 10:21:20 up 14:59,  0 users,  load average: 6.29, 6.85, 6.57
Tasks:  10 total,   1 running,   9 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.0 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem:  15360.00+total, 4391.152 used, 10968.84+free,    0.000 buffers
```
and the size of the index file is 20MB.

**Comment by yurymalkov** [comment]
@UpCoder That is strange. It seems like the file is corrupted (which would lead to this warning). Can you share it?
You can also try an earlier commit (`pip3 install --user git+https://github.com/nmslib/hnswlib.git@10273f5705c1e14f82c3c7466f688742db2051ff#subdirectory=python_bindings`).

**Comment by UpCoder** [comment]
Thank you!
It suddenly works for me...
The index file is [Google](https://drive.google.com/open?id=1O5pn9WMPuafC5sJxFqa02PgN4utLum2W)

**Comment by yurymalkov** [comment]
Great! I'll check it for problems...

**Comment by yurymalkov** [comment]
@UpCoder 

I've checked the file. The master version of hnswlib opens it without a problem...

**Comment by UpCoder** [comment]
@yurymalkov Thank you! Yes, the master branch works now. But I don't know what cause the error...

**Comment by yurymalkov** [comment]
@UpCoder removed this confusing message, should be a "file not found" / "corrupt index" messages instead. (`develop` branch)
