### ISSUE TITLE
the time-costing part in the lib

### ISSUE THREAD

**Issue by chasingegg** [nmslib/hnswlib#150]
Hi, your job is very great! I have some questions.

For this library, I count the distance computations and simulate the same number of distance computations to count time to see if distance computation dominates the whole algorithm running time, it seems that it only takes about 1/5 of the algorithm, is that reasonable? So what is the most time-costing part of the algorithm? And if you have better idea to know the running time of different parts of the algorithm elegantly, please let me know, thanks a lot!

**Comment by yurymalkov** [comment]
HI @chasingegg ,
It highly depends on the input. What is your data?
I suppose that for a million size dataset with d>200 Euclid space most time should be spent during the distance computations. On the other hand, for low dimensional data, the overhead should be the major contributor.

**Comment by chasingegg** [comment]
Hi, @yurymalkov ,
I use SIFT1m dataset(dimension=128), maybe I could also test on the GIST1M dataset(dimension=960).
Again, do you have a better idea to get the insight of the most time-costing part in the algorithm?

**Comment by yurymalkov** [comment]
@chasingegg It seems a bit strange... I'll check the ratio for SIFT1M.
The most consuming part for low dimensional data is usually memory lookups (for data and the visited flag) and operation on priority queues in the search structure.
