### ISSUE TITLE
Merging different index files

### ISSUE THREAD

**Issue by walekarketaki8** [nmslib/hnswlib#157]
Instead of loading previous index and add_items to that. Is there any possible way to merge different index.bin files?

**Comment by yurymalkov** [comment]
Hi @walekarketaki8,
You can potentially do that, but it will be as slow as using `add_items`, since the graphs are have to be rewired.

**Comment by walekarketaki8** [comment]
Is there any way to make this add_items fast? Since we are having around 1GB  index file and to add something in that is taking way too much time.

**Comment by yurymalkov** [comment]
@walekarketaki8 
By "something" do you mean a batch of elements or a whole index? You can incrementally add elements to your index.

**Comment by walekarketaki8** [comment]
But its time consuming....currently we are doing that only 'incrementally add elements to index.'
but its taking much time

**Comment by yurymalkov** [comment]
@walekarketaki8 The `add_items` time can possibly be reduced via optimization, however, I do not see any simple solution to make it fast.

**Comment by walekarketaki8** [comment]
What kind of optimisation do u suggest?

**Comment by DoanThu** [comment]
> Hi @walekarketaki8,
> You can potentially do that, but it will be as slow as using `add_items`, since the graphs are have to be rewired.

Do you have any sample code that merges 2 different index files?

**Comment by yurymalkov** [comment]
@walekarketaki8 
There are lots of possible small optimizations.
E.g. it seems that during insertion of an element, the links should be added starting from the bottom layer, not from the above.
The trick with more controlled selection of layers can be adopted from Faiss' HNSW implementation.
Some tuning and profiling would also help.

**Comment by walekarketaki8** [comment]
.get_items() is empty list. 

index = hnswlib.Index(space='l2', dim=186)
index.load_index('x.bin')
max_elem = len(index.get_ids_list())
index.load_index('x.bin', max_elements=max_elem)
item1= index.get_items()

**Comment by walekarketaki8** [comment]
> @DoanThu
> A simple way to do it is just load all indexes and add the elements of one index into another (e.g. using `get_items` for index 2 and then `add_items` for index 1).
> In C++ merging can be done somewhat faster, but not dramatically.

get_items() is empty list.

index = hnswlib.Index(space='l2', dim=186)
index.load_index('x.bin')
max_elem = len(index.get_ids_list())
index.load_index('x.bin', max_elements=max_elem)
item1= index.get_items()

**Comment by yurymalkov** [comment]
@walekarketaki8 Hmm. Will look into that.

**Comment by walekarketaki8** [comment]
> @walekarketaki8 Hmm. Will look into that.

Thanks for the replay. By the way for the above problem here is more detail explanation

index1 = hnswlib.Index(space='l2', dim=186)
index1.load_index('file1.bin')
max_elem = len(index1.get_ids_list())
index1.load_index('file1.bin', max_elements=max_elem+24971)

index2 = hnswlib.Index(space='l2', dim=186)
index2.load_index('file2.bin', max_elements=24971)

After doing (index2.get_items()) gives []
But index2.get_items([0]) gives [[.....]] 186 dimension vector

Problem is after doing 
index1.add_items(index2.get_items()) 
getting RuntimeError: The number of elements exceeds the specified limit

**Comment by walekarketaki8** [comment]
> @walekarketaki8 Hmm. Will look into that.

I found the issue. Able to solve the merging with get_items() and add_items()

**Comment by yurymalkov** [comment]
Great!
