### ISSUE TITLE
Accuracy Problems with Larger Datasets

### ISSUE THREAD

**Issue by mwade625** [nmslib/hnswlib#164]
I have created a matrix with 300 dimensions x 70,000 documents (L2 normalized Latent Semantic Vectors).  With this data set using M of 300 and efConstruction of 400, I get 99.671% accuracy on retrieving the top 300 items with efSearch of 400.  efSearch = 100, I get 82%.  

NOTE: using HNSW and "consinesimil"  when building the index.

With an M value of 96, and all other parameters the same I get an accuracy of 80.03% for efSearch of 400 and %80.8 for an efSearch value of 1600.

ISSUES:

1.  When I increase the # of items to 6,000,000 my results are terrible, even with large values of M (300 or more).  Exactly the same kind of data, just a lot more of it.    
2.  The guidance for setting M and efConstruction size (or just overiding maxM0) is very minimal but seems to suggest that the M value should not need to be so large.  I am guessing that the issue is due to having a very large number of similar documents.

Is there better guidance on setting these values or do I need to know the inrinsic amount of similarity in the data collection to put together "optimal" settings?  I was thining of doing a random sample of data and get some real measurements and then use that to predict the best parameters.

Any help would be greatly appreciated.

Mike

**Comment by yurymalkov** [comment]
@mwade625 
Are there any duplicates in the data (they might cause such problem)? Can you share a portion of the dataset?

Yes, real measurement is the best option. 
If practical M is very large, I really doubt it should be significantly faster than the brute-force approach. A rough estimate gives: 400 (efConstruction)* 300 efSearch ~ 120k evaluated points which is comparable to the size of the dataset.

**Comment by mwade625** [comment]
Some of the items have a large number of duplicates (hundreds to low thousands).  These are not usually 100% duplicate, but fairly similar as measured by the cosine similarity.  Just to be clear the 70K documents set works very well, but that 6 million document set does not.  I was really looking to leverage this approach for my very large datasets. My LSH code takes about 5 days to calculate the similarities for the 6 million document set.  I was hoping to find a better way, 

Thanks for your response, greatly appreciated.

For the dataset, I can share anything that would be helpful, it is all public data.  Let me know what would be most helpful and I can upload it ( the simialrity data itself, or just the nmslib index.

**Comment by yurymalkov** [comment]
@mwade625 Thank you! 
It would be nice if you share the dataset to look what is happening there.

**Comment by n-gao** [comment]
I also experience really bad performance on very large datasets. I tried running it on a dataset of 80.000.000x800 with M: 48 and ef_construction: 1000. When querying with ef: 60.000 for k=100 my recall is 0.
Are there estimates for how to choose M and ef_construction for very large datasets?

**Comment by yurymalkov** [comment]
@n-gao 
Do you have duplicates at the database?

**Comment by n-gao** [comment]
Yes, it contains some duplicates and very similar items.

**Comment by yurymalkov** [comment]
Ok. It is strange then. The recall should not at least `M*ef/(dataset_size)=0.075`, assuming extremely high dimensional data.
Did you look at how recall degrades with the size of the dataset?

**Comment by n-gao** [comment]
I will investigate that but it may take some days. Based on your knowledge what would be fitting parameter for ef and M to achieve a good recall (at least 0.5)?

**Comment by yurymalkov** [comment]
The `M` and `ef` highly depend on the internal structure of the dataset. If you have high dimensionality, `M` should be set as high as the memory allows. There is no clear rule how to set `ef` other than measuring the recall.

**Comment by n-gao** [comment]
It worked on a smaller seized dataset with M=48. On the whole 80M dataset it worked when setting M=400.

**Comment by searchivarius** [comment]
@n-gao I am very curious how does it work on something in between. Which M is required for say a 5M data set.

**Comment by n-gao** [comment]
It turned our to be an error on me keeping track of the indices. It works with all values of M in the range of 6 to 48 as written in the paper

**Comment by yurymalkov** [comment]
@n-gao 
Got it! Closing the issue.
