### ISSUE TITLE
C++ Example

### ISSUE THREAD

**Issue by ashfaq92** [nmslib/hnswlib#167]
Hi!
 In your "readme.md" and "examples" folder, examples are provided only with python bindings. 
In [https://github.com/jlmelville/rcpphnsw](https://github.com/jlmelville/rcpphnsw) rough equivalent of the serialization/deserialization example from this hnswlib README file is provided in 'R' language.
But nowhere C++ example of serialization/deserialization equivalent to current README example is provided. I want to use hnswlib in my c++ project. I was wondering how to do the exact functionality in c++.  It would be great if you translate examples given in python to c++.
Thank you!

**Comment by yurymalkov** [comment]
@ashfaq92 

Thanks for noticing! I'll make an example.

**Comment by jlmelville** [comment]
The basics of creating/re-sizing/re-loading an index, as used in RcppHNSW are below. It doesn't really do anything, but it *should* compile and run without causing your computer to explode, which is 90% of the battle in C++. Hopefully you can work out the rest!

```C++
#include <memory>
#include "hnswlib.h"
void example()
  auto dim = 16;
  auto num_elements = 100000;
  auto init_num_elements = num_elements / 2;
  auto M = 16;
  auto ef_construction = 200;

  using dist_t = float;
  using Distance = hnswlib::L2Space;

  // create the index
  auto space = std::unique_ptr<Distance>(new Distance(dim));
  auto appr_alg = std::unique_ptr<hnswlib::HierarchicalNSW<dist_t>>(
    new hnswlib::HierarchicalNSW<dist_t>(space.get(), init_num_elements, M,
                                         ef_construction));

  // resize it
  appr_alg->resizeIndex(num_elements);

  // or save and reload it
  std::string path_to_index = "myindex.hnsw";
  appr_alg->saveIndex(path_to_index);
  appr_alg.reset(new hnswlib::HierarchicalNSW<dist_t>(space.get(), path_to_index));
};
```

**Comment by ashfaq92** [comment]
@jlmelville thanks for prompt response. Sorry for late reply due to "timezones :(". I have run your code and it works without error (as you said :). But it would be really nice if you update this code according to the readme file. I mean if it make HNSW graph with random numbers and finds nearest neighbor for any random query point. Then we may add this code in readme files so that future c++ beginners may embed that in their code (like me).

**Comment by Akshaysharma29** [comment]
With the addition to above code
`auto dim = 512;
    auto num_elements = 100000;
    auto init_num_elements = num_elements / 2;
    auto M = 16;
    auto ef_construction = 200;

    using dist_t = float;
    using Distance = hnswlib::L2Space;

    // create the index
    auto space = std::unique_ptr<Distance>(new Distance(dim));
    auto appr_alg = std::unique_ptr<hnswlib::HierarchicalNSW<dist_t>>(
            new hnswlib::HierarchicalNSW<dist_t>(space.get(), init_num_elements, M,
                                                 ef_construction));

//    // resize it
////    appr_alg->resizeIndex(num_elements);
    typedef size_t labeltype;
    appr_alg->setEf(200);
    auto ret=appr_alg->searchKnn(default_emb,1);//'1' is the nearest neg

    std::vector<std::pair<dist_t, labeltype>> result;//result return after knn search
//    while (!ret.empty()) {
//        result.push_back(ret.top());
//        ret.pop();
//    }


    int f=0;
    int id_label;
    float mn=100000;
    if(ret.size()==0)
    {
        counter_value+=1;
        appr_alg->addPoint(default_emb,counter_value);
        LOGD("This is empty ret");
    } else{
        LOGD("Non empty ret");
        while (!ret.empty()) {
            result.push_back(ret.top());
            ret.pop();
        }
        for(int i =0;i<result.size();i++)
        {
            LOGD("hnswlib result:(1)distance:) %f => (2)label:) %d",result[i].first,result[i].second);
            if(result[i].first<(0.5)&&mn>result[i].first)
            {
                f=1;
                mn=result[i].first;
                id_label=result[i].second;
            }
        }
        if(f==0){
            counter_value+=1;
            id_label=counter_value;
            appr_alg->addPoint(default_emb,counter_value);
            LOGD("New entry generated");
        }else{
            LOGD("Id we get:%d",id_label);
        }
    }

    result.clear();`
