### ISSUE TITLE
how to load several files which is saved by "saveIndex" into a "HierarchicalNSW<float>" variable?

### ISSUE THREAD

**Issue by merria28** [nmslib/hnswlib#178]
I have saved several ".bin" files by function "saveIndex".
Now I need load some of  ".bin" file into one variable of HierarchicalNSW.
How should I do?

**Comment by yurymalkov** [comment]
@merria28 

Currently, there is only one way to do it via python:


1) You should the first index.

2) Load the second index. Iterate over the data in the second index and insert into the first index.  

Repeat step 2) for all other indices.
