### ISSUE TITLE
MemoryError when loading an index

### ISSUE THREAD

**Issue by n-gao** [nmslib/hnswlib#180]
Hi,

I want to use hnsw for ANN search in a dataset with roughly 80.000.000 items of dimensionalities of around 700. Creating the index works but takes very long on a machine with 128GB of RAM. However, when loading the dataset on a machine with 384GB of RAM I get the following error:
```
Warning: loading of old indexes will be deprecated before 2019.
Please resave the index in the new format.
Traceback (most recent call last):
  File "search_speedup.py", line 193, in <module>
    main(parser.parse_args())
  File "/home6/ngao/miniconda3/envs/python2/lib/python2.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "search_speedup.py", line 48, in main
    hnsw_index.load_index(p)
MemoryError: std::bad_alloc
```
Why does the loading of a preconstructed index require more RAM than creating and saving it?

I wanted to do a small hyperparameter search, the smallest values I used where:
M: 12, EF: 1000 up to M: 96, EF:1000

Thank you!

**Comment by yurymalkov** [comment]
Hi @n-gao,
I think the saved index might be corrupt or the path to the index is wrong. 

`Warning: loading of old indexes will be deprecated before 2019.` is a misleading warning (should already be fixed in `master`)

You can also try the version of the code from `master`, it should give you a normal error.

**Comment by n-gao** [comment]
I installed it via `pip` about 2 weeks ago, does that differ from `master`?

**Comment by yurymalkov** [comment]
@n-gao 
Yes. I'll try to update the pip version today.

**Comment by n-gao** [comment]
Turns out my path was incorrect, the error message is misleading and should probably be more specific. Thank you!
