### ISSUE TITLE
Some confusion?

### ISSUE THREAD

**Issue by dongzhen123** [nmslib/hnswlib#182]
1.As the paper show:
M-number of established connections
Mmax-maximun number of connections for each element per layer(except l0)
Mmax0-maximun number of connections for each element in l0
so the quantitaive relationship between them is what?
what I know is Mmax0=2*Mmax.   but then the relationship between Mmax and M is what?

2.How to export the id of neighbors of one vertex in the graph in python?

**Comment by yurymalkov** [comment]
Hi @dongzhen123 ,
1. By default Mmax=M
2. There is no way to do that now, but, it should be quite easy to implement.

**Comment by dongzhen123** [comment]
> Hi @dongzhen123 ,
> 
> 1. By default Mmax=M
> 2. There is no way to do that now, but, it should be quite easy to implement.

thanks for your reply.then
1.for l0 and other l,the M is same?the difference is that Mmax0=2*M and Mmax=M?
2.can you give a example to implement it?

**Comment by yurymalkov** [comment]
@dongzhen123 
Sorry for the delay. 
Yes, I can guide through the process.

**Comment by dongzhen123** [comment]
> @dongzhen123
> Sorry for the delay.
> Yes, I can guide through the process.

I found some strange thing, and have a look in https://github.com/nmslib/hnswlib/issues/185 in detail.thank you~
