### ISSUE TITLE
License for Java Implementation

### ISSUE THREAD

**Issue by ashfaq92** [nmslib/hnswlib#183]
Hi, I have used HNSW's [Java Implementation](https://github.com/jelmerk/hnswlib)referenced in your Readme file for academia. That java implementation is missing License file. But in POM.xml file, apache license is included. Does that implementation comes under same license as this project ?. Moreover, does the pom.xml license covers whole license or or we have to ask for separate license. Please explain
![license](https://user-images.githubusercontent.com/28701122/71777256-72948980-2fd8-11ea-85c7-43aed611811b.PNG)

**Comment by yurymalkov** [comment]
Hi @ashfaq92,
I think you should ask the authors of the Java implementation.
