### ISSUE TITLE
How to set up the size of indexing data which is less than one million in SIFT dataset?

### ISSUE THREAD

**Issue by Jiawen1991** [nmslib/hnswlib#184]
By changing the parameter "subset_size_milllions" in file sift_1b.cpp, hnsw can support from 1M to 1B indexing data size.

When I changed the parameter "vecsize" and tried to set up the number of indexing data less than 1M, the recall (for querying) is very low (or incorrect). Is there any approachs to set up the size of indexing data which is less than one million in SIFT dataset and to keep the correct recall?

Any comments are welcome.

Thanks!

**Comment by yurymalkov** [comment]
Hi @Jiawen1991,

Thinks there is no ground-truth for dataset less than 1 million (the dataset has the GT only for some subsets of a billion), so the code should not be working.

**Comment by yurymalkov** [comment]
You can probably, compute the gt inside the code, instead of loading it from a file.

**Comment by Jiawen1991** [comment]
Thank you!
