### ISSUE TITLE
Maybe find a bug?

### ISSUE THREAD

**Issue by dongzhen123** [nmslib/hnswlib#185]
Take a closer look at the code,for example:
###############
import hnswlib
dim=64
num_elements=1000000
p=hnswlib.Index(space='l2,dim=dim)
p.load_index("**.bin")
################
we could use p.get_items([num])  to get the num-th value in the database.

but take a closer look at hnswalg.h  , we could also get this valuse in the following way,and the following way "getDataByInternalId" is also the way to get the data and then calculate the distance between query and database in search phase in hnswalg.h :
############
std::vector<float> get_data(size_t a){
      std::vector<float> v;
      for (size_t i=0;i<64;i++){
           const void *dz=getDataByInternalId(a);
           v.push_back(((float*)dz)[i]);
       }
       return v;
 }
###############

 In all num_elements=1000000 the two way get the data most is same,but 19015 is different in my experiment.
##########
sum=0
for i in range(num_elements):
     a=np.array(p.get_data(i))
     b=np.array(p.get_items([i]))
     d=np.linalg.norm((a-b))
     if d>1e-5:
         print(i,d)
         sum+=1
print(sum)#sum=19015
###########
the different way is that,the number is indice in database:

num                         getDataByInternalId                       get_items  
...
287                                 288                                          287
288                                 287                                          288
.....

**Comment by yurymalkov** [comment]
Not sure if I understood. 
Ids for python (labels) and internal ids are different. 
You can get the label from an internal id (https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L130) or vise versa (https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L724)

**Comment by dongzhen123** [comment]
> Not sure if I understood.
> Ids for python (labels) and internal ids are different.
> You can get the label from an internal id (https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L130) or vise versa (https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L724)

yeah,solve it !thanks~
I misthink that Ids for python (labels) and internal ids are same by default.
