### ISSUE TITLE
modifying the value of a certain label doesn't change the ranking

### ISSUE THREAD

**Issue by alexcarterkarsus** [nmslib/hnswlib#190]
Hello,
I have been using hnswlib's python binding and encountered the following issue: 
After one item has been added with a label, I tried to change its value by 'adding' the different value with the same label:
import hnswlib 
vectors = [np.array([1,1,1,1]),np.array([1,1,1,0.95]),np.array([1,1,1,0.9]), np.array([1,1,1,0.85])] 
vectorsInput = np.array(vectors) 
t = hnswlib.Index(space = 'cosine', dim = 4) 
t.init_index(max_elements = 100, ef_construction = 300, M = 16) 
t.add_items(vectorsInput, [1,2,3,4]) 
h,s = t.knn_query(np.array([1,1,1,1]),k=3, num_threads=1) 
print(h)

this gives correctly order of 3 closest items:
[1,2,3]
now, I want to change the item with label '2' with a new vector [0,0,0,0]:
 t.add_items(np.array([0,0,0,0]), [2])

this obviously has changed the value of the item itself, and consequently should change the order of the 3 closest items as well, which we would expect to be [1,3,4], however:
h,s = t.knn_query(np.array([1,1,1,1]),k=3, num_threads=1) 
print(h)

we still get:
[1,2,3]
which is obviously wrong. 

Incidentally I have tested with the C++ code and did exactly the same thing, but the output was correctly [1,3,4].

which would mean there is something wrong with the python binding, right? 
Thanks!

**Comment by yurymalkov** [comment]
Hi @alexcarterkarsus,

Thank you for reporting!

I will look into it when I return from traveling.

**Comment by yurymalkov** [comment]
Hm, cannot reproduce...
The code 
```
import hnswlib
import numpy as np
vectors = [np.array([1,1,1,1]),np.array([1,1,1,0.95]),np.array([1,1,1,0.9]), np$
vectorsInput = np.array(vectors)
t = hnswlib.Index(space = 'cosine', dim = 4)
t.init_index(max_elements = 100, ef_construction = 300, M = 16)
t.add_items(vectorsInput, [1,2,3,4])
h,s = t.knn_query(np.array([1,1,1,1]),k=3, num_threads=1)
print(h)

t.add_items(np.array([0,0,0,0]), [2])

h,s = t.knn_query(np.array([1,1,1,1]),k=3, num_threads=1)
print(h)
```

Outputs as expected:
```[[1 2 3]]
[[1 3 4]]```


Are you using the master version of the code?

**Comment by alexcarterkarsus** [comment]
ahhh I was using 0.3.2, after upgrading to 0.3.4 it is working as intended. Thanks!

**Comment by yurymalkov** [comment]
@alexcarterkarsus 
Great! There was indeed a bug in 0.3.2.
