### ISSUE TITLE
Does HNSW support KNN join?

### ISSUE THREAD

**Issue by jiawen11** [nmslib/hnswlib#193]
"k nearest neighbor join (kNN join), designed to find k nearest neighbors from a dataset S for every object in another dataset R, is a primitive operation widely adopted by many data mining applications. "

Whether HNSW supports KNN join or not?

Any comments are welcome.

Thanks!

**Comment by yurymalkov** [comment]
Hi @jiawen11 ,
Based on your description, the library does support that as a batch knn query.

**Comment by jiawen11** [comment]
Thank you for your reply, Yury!

Do you mind describe more detains of how to perform the knn join between two datasets, e.g., find k nearest neighbors from SIFT from GloVe, by batch knn query? 

Thanks!

**Comment by yurymalkov** [comment]
@jiawen11 
I do not think you can do this operation between SIFT and GloVe, as they have different nature (particularly, different dimensionality).

I think you can do this operation between subsets of a dataset, e.g. between subset of SIFT.

**Comment by jiawen11** [comment]
Thanks
