### ISSUE TITLE
Is there an implementation of HNSW for GPU with CUDA?

### ISSUE THREAD

**Issue by jiawen11** [nmslib/hnswlib#194]
I am wondering whether or not there is an implementation of HNSW for GPU with CUDA?

If so, do you know where I can obtain the code and how the performance looks like?

If not:
1. Is it possible for HNSW to be executed on GPU? 
2. What is the most challenging part of converting HNSW on GPU?
3. When I reviewed the code, the parallel section is implemented by OpenMP now. Is that part of code worth to be executed on GPU by rewriting the code with CUDA? The purpose is to speed up the construction (indexing) phase.
4. For query, do you think HNSW can be speed up by executing on GPU?

Any comments are welcome.

Thanks!

**Comment by yurymalkov** [comment]
Hi @jiawen11 ,

As far as I know there was an implementation of HNSW on CUDA inside Amazon (some paper mentioned it). GPUs has significantly different architectures compared to CPUs, so a significant overhaul of the algorithm is needed to make it efficient (e.g. batched graph traversal).

I am also recommend checking out https://github.com/cgtuebingen/ggnn

**Comment by jiawen11** [comment]
Thank you for your response!

**Comment by js1010** [comment]
@jiawen11 @yurymalkov https://github.com/js1010/cuhnsw here is the cuda implementation of hnsw, hope that it is helpful for you.

**Comment by yurymalkov** [comment]
@js1010 Great work, thanks! Going to test it!
