### ISSUE TITLE
Theoretical analysis for inferring query recall and time

### ISSUE THREAD

**Issue by jiawen11** [nmslib/hnswlib#196]
Is it possible to have an analytical model or theoretical analysis to infer the query recall and time? For example:

1. If I am incrementally indexing HNSW with SIFT 2M, is it possible to obtain the query recall and query time of SIFT 1M with theoretical analysis instead of running the real prediction test?

2. If I am incrementally indexing HNSW with SIFT 1M, is it possible to infer the query recall and query time of SIFT 2M?

Any comments are welcome.
Thanks!

**Comment by yurymalkov** [comment]
Hi @jiawen11,
You can potentially analyze the performance of the method analytically on random data(at least under some assumptions), but for SIFT I think the main problem is how do you model it.

**Comment by jiawen11** [comment]
Hi @yurymalkov,

In your paper (Fig. 13 and Fig. 14), I observed that the recall and query time vary a lot. For my understanding, the difference in data size, dimensions, space calculation, ef_construciton, M, ef and M_max, are the main reasons for different query recall and time.

I have the following questions and hope you have any ideas of the reason:
1. Am I correct for the above assumption?
2. What do other elements impact query recall and time? (For example, the range of value of the dataset, the number of layers)
3. Is it possible to build a model to infer the query accuracy for different datasets with different features?

Thanks!

**Comment by yurymalkov** [comment]
@jiawen11 
Not sure if it still needed:
1) Yes, you are correct
2-3) I am not sure that those features are enough to characterize a dataset. I would look at the clustering coefficients of a k-nearest neighbor graph at different scales to assess the complexity of a dataset.
