### ISSUE TITLE
How could I use HNSW for other datasets, e.g., GloVe and DEEP, with the C++ implementation?

### ISSUE THREAD

**Issue by jiawen11** [nmslib/hnswlib#198]
Hi,

How could I use HNSW for other datasets, e.g., GloVe and DEEP, with the C++ implementation?

Any comments are welcome.
Thanks!

**Comment by yurymalkov** [comment]
Sure, you can use HNSW with all those datasets.
The only differences with sift are:
* distance data type (float instead of int)
* different distance function (cosine instead of integer L2)

**Comment by jiawen11** [comment]
> Sure, you can use HNSW with all those datasets.
> The only differences with sift are:
> 
> * distance data type (float instead of int)
> * different distance function (cosine instead of integer L2)

Hi Yury,

I found the datasets, e.g., GloVe and DEEP, from https://github.com/erikbern/ann-benchmarks but they are only with the format of HDF5 for Python implementation instead of bvecs and ivecs for C++ implementation. 

Do you know where I can find those implementation of deploying HDF5 format (e.g., GloVe and DEEP) for HNSW C++ version instead of Python? 

Thank you so much in advance for your help!

**Comment by yurymalkov** [comment]
Hi @jiawen11,

I think, a proper way is to open those datasets in python and save them in binary format which is easily read from C++.
