### ISSUE TITLE
range search

### ISSUE THREAD

**Issue by wuwenjunwwj** [nmslib/hnswlib#199]
do you have any plans to support range search?

**Comment by yurymalkov** [comment]
That it not in the current plans.
This repository potentially have what you want:
https://github.com/generall/cat_hnswlib/blob/master/CATEGORIES.md

**Comment by wuwenjunwwj** [comment]
> That it not in the current plans.
> This repository potentially have what you want:
> https://github.com/generall/cat_hnswlib/blob/master/CATEGORIES.md

Thank you for you replay， it's a good inspiration

**Comment by wuwenjunwwj** [comment]
> That it not in the current plans.
> This repository potentially have what you want:
> https://github.com/generall/cat_hnswlib/blob/master/CATEGORIES.md

Thanks for your reply，it's a good inspiration for me
