### ISSUE TITLE
strange behaviour with get_items and cosine distance

### ISSUE THREAD

**Issue by stavinsky** [nmslib/hnswlib#203]
```
dim = 5
num_elements = 10000
data = np.float32(np.random.random((num_elements, dim)))
data_labels = np.arange(num_elements)
p = hnswlib.Index(space = 'cosine', dim = dim)
p.init_index(max_elements = num_elements, ef_construction = 300, M = 64)
p.add_items(data, data_labels)
print(data[139] == p.get_items([139]))
```
```
[[False False False False False]]
```
always gives falses, 
but with l2 metric always gives trues

```
dim = 5
num_elements = 10000
data = np.float32(np.random.random((num_elements, dim)))
data_labels = np.arange(num_elements)
p = hnswlib.Index(space = 'l2', dim = dim)
p.init_index(max_elements = num_elements, ef_construction = 300, M = 64)
p.add_items(data, data_labels)
print(data[139] == p.get_items([139]))
```
```[[ True  True  True  True  True]]```

**Comment by yurymalkov** [comment]
HI @stavinsky,

Thanks for reporting.
This happens because hnswlib normalizes the vectors before storing them for cosine similarity. Otherwise, it would require much more memory, or some loss of performance. So not sure what to do about it (other than updating the readme).

**Comment by stavinsky** [comment]
ok. Now I understand. I was trying to get origin vector only because I wanted to try recalculate cosine distance after knn query. I thought it will improve qualty in my project. 

By the way, thanks for very fast answer. And yes, I thinkg we should update readme. I'm not the one who will want to get source vector

**Comment by yurymalkov** [comment]
@stavinsky Got it. Will update the readme.
