### ISSUE TITLE
search results are different everytime

### ISSUE THREAD

**Issue by suimo** [nmslib/hnswlib#209]
Hi, I build a index with hnswlib::HierarchicalNSW in L2Space. then I search 300 3-d points and get 300
priority_queues, I find that the result of every search is different, Is this reasonable? please give me some advice, thanks a lot!

**Comment by yurymalkov** [comment]
Hi suimo,
Have you been able to resolve the problem? 
I also wonder, you tried to use hnswlib specifically to 3D points?

**Comment by suimo** [comment]
Hi, thanks for your reply.
please take attention to my new issue #208, thanks
