### ISSUE TITLE
Item itself returned twice with knn_query

### ISSUE THREAD

**Issue by fabero** [nmslib/hnswlib#236]
Good afternoon,

I am using hnswlib to find texts with similar embeddings. In some cases, it seems like knn_query is returning the element which is the query twice instead of only as the first item.

The resulting labels and distances would then look like this:

`
labels = [['id1', 'id1, 'id2']]
`
`
distances = [[-1.1920929e-07  0.0000000e+00  5.5412829e-01]]
`

Is this caused by the precision of the distances or something? And how would I prevent this?

I am using the solution proposed in #30 to be able to use strings as ids, and built the index as follows:

`
index = hnswlib.Index(space='l2', dim=dim)
`
`
index.init_index(max_elements=num_elements, ef_construction=100, M=16)
`
`
index.add_items(data, labels)
index.set_ef(50)
`

Thanks in advance!

**Comment by yurymalkov** [comment]
Hey @fabero 
That is very strange... Ids should be unique.
Can you please get a reproducible example?

**Comment by fabero** [comment]
It turns out the bug was in was my own code. I built the index including the vector which would later be the query. The ID seemed to be returned twice because of this, but this was not the case. Sorry for wasting your time!
