### ISSUE TITLE
cosine: sometimes distances are all 1

### ISSUE THREAD

**Issue by inkrement** [nmslib/hnswlib#238]
In some cases all k (cosine) distances are one (1.), which is not really plausible. Is there a hyper parameter to tune or could it be related to a bug? At the moment I do not really know how to debug it properly. 

Update:I already checked the data set and there are indeed some "similar" vectors, so it seems like a bug or a poor hyper parameter selection.

**Comment by yurymalkov** [comment]
Hi @inkrement!
Yes, that is not normal. 
Can you calculate the distance to the returned vectors (by using ids) and compare it to the distances outputted by the library?

**Comment by inkrement** [comment]
Sorry for the late reply. Due to upcoming deadlines I temporarily switched to another library. Nevertheless, I just checked it and seems like the cosine similarities are calculated wrongly. Could it be the case, that the library is just able to find the best "in-sample" matches? I want to find nearest neighbours for new (previously) unseen vectors. Or does it assume unit-vectors as input?

**Comment by yurymalkov** [comment]
@inkrement thanks for the reply!
It does not assume unit-vector input and it should works for new (previously) unseen vectors, so not sure what is the problem. Can you share the data?

**Comment by inkrement** [comment]
@yurymalkov The data cannot be made available to the public. However, I could share it with you via mail.

**Comment by yurymalkov** [comment]
Ok! Please sent me at `my github login` at mail dot ru.
I'll look at it during the weekend. Thanks!

**Comment by inkrement** [comment]
Hi, I just wanted to reproduce it, but now it seems to work. Really strange.. However, thanks for the great support! I'll close the issue for now.
