### ISSUE TITLE
if nearest points needed immediately after adding new points?

### ISSUE THREAD

**Issue by qumingzhentmnan** [nmslib/hnswlib#240]
Hello everyone,

i was wondering if there is a more efficient way in this case?

The moment after adding new points into graph, i need the top k( less than m and ef)  nearest neighbors for exactly these new points before adding other new points. 
in short, i need the knn of these points immediately after adding them.
It seems natural to _add_items_ first and then _knn_query_.

However, i think  _searchBaseLayer_  when building graph does similar things in _knn_query_.
In the code, _top_candidates_ are sorted by distance **before** doing heuristic select. I print several  top k elements in _top_candidates_ when adding new points and they are equal with the results doing knn_query. 

I mean will the immediate queried nearest points have some connection with the points stored in top candidates? I have a feeling that it has... if so, will it be more efficient to get top k directly from _top_candidates_ than querying them later?

Any help would be greatly appreciated.

**Comment by yurymalkov** [comment]
Hi @qumingzhentmnan,
Yes, it would be more efficient to extract them from the `searchBaseLayer` before the heuristic.
Probably the difference compared to additional querying is not that big, since you the removed edges by the heuristic should be easily retrieved (compared to a search for a different element, e.g. random). But this is an unnecessary  overhead.

**Comment by qumingzhentmnan** [comment]
Thank you for your reply! 

Let me see if I understand you correctly. You mean i can get k nearest elements before _heuristic_ without extra _knn_query_ ? 

After i submitted this issue, i further test this on 10M dataset. However, comparing to _knn_query_ results, the results in _top_candidates_(before heuristic) are less accurate and miss several nearer points.  It puzzles me.

As i modify your code a little bit, maybe i made some mistake during modification. 
So, i want to make sure it theoretically correct to omit knn_query.

Many thanks,

**Comment by yurymalkov** [comment]
Hi @qumingzhentmnan,
Yes, the accuracy should be very similar (on average). There might be some subtile factors, but even if there is a slight performance difference it should be negated by slightly altering ef_construntion.
If the difference is large that should be investigated, it should not be so.

**Comment by qumingzhentmnan** [comment]
Thank you so much for your reply! 

Yes, you are right!
Maybe it is because i set _ef_ two times lager than _ef_constrction_, and misses some points in _top_candidates_ doing _add_items_. I get same result after setting _ef_constrction_ = _ef_ =200 (vector dim = 512).

Well, at first, i hope to get knn directly so to save time spent on _knn_query_. However, it seems that i have to set larger _ef_constrction_ to get same results, leading more time on building index. 
I don't know whether to laugh or cry for this result. I may go deeper to find out how much time can be saved if getting it directly with larger _ef_constrction_. I hope for improvement as it seems to need more modification.... 

In your opinion, which could be faster, larger _ef_constrction_ and extract knn directly with no _knn_query_ part or _ef_constrction_ smaller than ef with extra _knn_query_?

What’s more, I am quite new to C++, if possible, can you give me some advice on how to get elements in _top_candidates_ and return them to python elegantly? A temporary _priority_queue_, like the one in _searchKnn_ ? if so ,gonna to change the type of function _addPoint_, seems a lot work.   

Many thanks!

**Comment by yurymalkov** [comment]
@qumingzhentmnan Sorry for a late reply. I can help with C++ instructions when needed.
Changing the type of `addPoint` should not be that hard. You can add a reference to a queue as an additional argument and copy to the nearest neighbors. This is a bit messy, but in case it is just a hack should not take too much time.

I think that larger `ef_construction` is better, but this is only a hypothesis.

**Comment by qumingzhentmnan** [comment]
Thank you for your reply! 

I further tested _ef_con_ =200 for 1m data.
it took 40% longer  doing _add_items_ comparing _ef_con_=100 for every new point, with slightly difference in _knn_query_. 

As index building time are greatly concerned and with no comparision of recall, the second option, _ef_con_ smaller than _ef_ with extra _knn_query_ seems faster than larger _ef_con_ .

Again, thanks for your great work. 

Ps:  data =1M, random data
![image](https://user-images.githubusercontent.com/57789793/91276921-bbda5900-e7b4-11ea-99dd-ccd3e97a735f.png)

**Comment by yurymalkov** [comment]
I see. Thanks for reporting!
