### ISSUE TITLE
Graph Construction: Neighbor Selection Error?

### ISSUE THREAD

**Issue by scott-weitze** [nmslib/hnswlib#248]
I found an issue with graph construction, where Hnsw selects a further vertex as a neighbor.  Using the sift dataset with 100 vectors and 128 feature dimensions, the Hnsw library selects neighbors following the adjacency list below.  The input parameters are M =8, and efConstruction=30.  The following output demonstrates vertex 9 adding elements {1,2,3,4,5,6,7,8} to its adjacency list.
```
* 0={1,2,3,4,5,6,7,8}
  1={0,2,3,4,5,6,7,8,9}
  2={0,1,3,4,5,6,7,8,9}
  3={0,1,2,4,5,6,7,8,9}
  4={0,2,1,3,5,6,7,8,9}
  5={0,2,4,1,3,6,7,8,9}
  6={0,2,5,4,1,3,7,8,9}
  7={0,2,5,6,4,1,3,8,9}
  8={0,5,1,2,4,3,7,6,9}
  9={8,6,2,3,1,4,7,5}
```
 
In python, I calculate the l2 distances from vertex 9 to each of the vertices. The output is sorted nearest to furthest. [(1, 294.8152), (3, 297.53152), (7, 303.7894), (5, 304.99017), (6, 329.51025), (0, 334.18707), (2, 334.43832), (8, 344.73178), (4, 364.05356)].  Is it correct that element 9 selects the adjacency list it does? According to the HNSW paper it would appear element 0 would be a better candidate for neighbor selection.

After element 9 is inserted, vertex 0 is still considered to be the entry point.
 
All elements are on the base level of the graph. I compiled with g++, using the default level generation seed.
 
Inputs: 
                    M_=8
                    maxM_=8
                    maxM0_=16
                    ef_construction_=30
 
Info: 
                    enterpoint_node_=38
                    max_elements_=100
                    mult_=0.480898
                    revSize_=2.07944
                    maxlevel_=2
 
Other:
                    offsetLevel0_=0
                    max_elements_=100
                    label_offset_=580
                    size_links_level0_=68
                    size_data_per_element_=588
                    size_links_per_element_=36

**Comment by searchivarius** [comment]
HNSW isn't supposed to build a neighborhood graph, but rather something resembling a relative neighborhood graph. So, some neighbors can be, indeed, pruned away.

**Comment by scott-weitze** [comment]
After reading the paper, I totally agree with the sentiment of your response. A relative neighborhood graph addresses the shortcomings of K-nearest neighbor graph, but I'm not sure the outcome  is that which is described in Hnsw. The heuristic pseudo-code of the paper seems to favor true nearest neighbors, not the graph diversification you are describing.

Following the logic of the heuristic from the paper, it would appear that the other vertex should be selected.  Is the logic of the implementation different from the heuristic described by the paper?

**Comment by searchivarius** [comment]
@scott-weitze I am not sure about the paper, but I cite: "The relative neighborhood graph of a set of points S ⊂ Ed is an undirected graph in which two points p and q are adjacent if there is no point that is simultaneously closer to both points." Arya & Mount 1993.
You keep adding data points in the order of increasing distance: x0 (center), x1 (first neighbor), ... ,xk
after adding the point xk you ignore all further points in the ball (xk, d(xk, x0)).
What could have happened, but it's not possible to tell without knowing mutla neighbor distances, is that point 0 was simply too close to point 5, 6 or any other previously added point. I hope this makes sense.

**Comment by scott-weitze** [comment]
I think that makes sense. Thank you for sharing the quote from Arya & Mount and your explanation, that helps my understanding. 

I'm closing the issue.
