### ISSUE TITLE
Find k nearest neighbors within a radius

### ISSUE THREAD

**Issue by Puumanamana** [nmslib/hnswlib#250]
Hi,

Is there a way to do a KNN search with a maximum distance constraint (in other words the k closest points within a certain radius)? I was initially using the [KDTree](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html#sklearn.neighbors.KDTree) from scikit-learn, but it's not as scalable as I'd want to. hnswlib seems to be much faster, but I can't find a way to do something similar as `query_radius()`
And if it is possible, can you even specify a different radius for each data point?

Thank you for your help!

**Comment by yurymalkov** [comment]
Hi @Puumanamana, unfortunately this functionality is not implemented. This requires some C++ coding (change of the stop condition).

**Comment by Puumanamana** [comment]
I see. Is it something that could be implemented in a more or less near future? Or would it require a lot of work?

**Comment by yurymalkov** [comment]
There are no concrete plans on this.
It does not require much work (change stop condition, some update in structures and python bindings) though if not trying to squeeze all of the performance.

**Comment by Puumanamana** [comment]
Thank you for the quick answers. I guess I'll have to find another tool
