### ISSUE TITLE
Fix typos in README.

### ISSUE THREAD

**Issue by ghuls** [nmslib/hnswlib#254]
Fix typos in README.

Change:
> Thanks to Apoorv Sharma @apoorv-sharma, hnswlib now supports true element updates (the interface remained the same, but when you the **perfromance**/memory should not degrade as you update the element **embeddinds**).
> 
> Thanks to Dmitry @2ooom, hnswlib got a boost in performance for vector dimensions that are not **mutiple** of 4

To:
> Thanks to Apoorv Sharma @apoorv-sharma, hnswlib now supports true element updates (the interface remained the same, but when you the performance/memory should not degrade as you update the element embeddings).
> 
> Thanks to Dmitry @2ooom, hnswlib got a boost in performance for vector dimensions that are not multiple of 4.

**Comment by yurymalkov** [comment]
@ghuls thanks for reporting. Those typos are already fixed in develop branch (#253 )
