### ISSUE TITLE
hnswlib recipe on conda-forge

### ISSUE THREAD

**Issue by yihming** [nmslib/hnswlib#268]
Hi All,

Bo Li (@bli25broad) and I have recently added `hnswlib` v0.4.0 to conda-forge.

When we were working on adding our Pegasus package to Bioconda, which uses hnswlib for kNN calculation. We found that there was no such package posted on either conda-forge or bioconda. Therefore, we had to add it ourselves to conda-forge.

The recipe is [here](https://github.com/conda-forge/hnswlib-feedstock), with hnswlib's python bindings included. And its package info on conda is [here](https://anaconda.org/conda-forge/hnswlib). It now supports linux64 and osx64, while win64 support is still on progress.

We just wonder if anyone from your team is interested in joining the recipe maintainer team of hnswlib. If so, please let us know, and we will add you there.

Thanks!

**Comment by yurymalkov** [comment]
Hi @yihming,
This is great! Thank you!
I can probably join and help, though I have a pretty limited capacity.

**Comment by yihming** [comment]
Hi @yurymalkov. Great to hear from you!

We will add you there in the next update.

**Comment by yurymalkov** [comment]
Cool! Thanks!

**Comment by yihming** [comment]
Hi @yurymalkov . Just let you know that I've added you to the maintainer team of hnswlib recipe on conda-forge.
