### ISSUE TITLE
why alloc memory +1?

### ISSUE THREAD

**Issue by Rainlolthx** [nmslib/hnswlib#270]
Hello, I am confused about the line 1033 in hnswalg.h
            if (curlevel) {
                linkLists_[cur_c] = (char *) malloc(size_links_per_element_ * curlevel + 1);
                if (linkLists_[cur_c] == nullptr)
                    throw std::runtime_error("Not enough memory: addPoint failed to allocate linklist");
                memset(linkLists_[cur_c], 0, size_links_per_element_ * curlevel + 1);
            }
when alloc memory for higher level, why is there need to add 1?
Can someone explain this?

**Comment by yurymalkov** [comment]
Hi @Rainlolthx,
This has been asked before in #176 
As far as I remember that is to avoid code analysis errors caused by the prefetch operation during search.

**Comment by Rainlolthx** [comment]
Thanks for your reply!
