### ISSUE TITLE
How to search from 20M vectors and How much Memory would it take to save 20M vectors of size 2048?

### ISSUE THREAD

**Issue by deshwalmahesh** [nmslib/hnswlib#277]
I followed your work and got the idea that how it's done. I have Embeddings from `ResNet` which is a 2048 length vector. I got an approximation that it within a search span of 17M vectors, with default configuration, it takes less than 1 second. That is pretty decent for me. But I want to know what would be the size of this data structure? How would it work? IF I save 20M vectors in my memory, it'll blow.

I tried something:
```
dim = 2048
num_elements = 10000

# Generating sample dat
data = np.float32(np.random.random((num_elements, dim)))

data1 = data[:num_elements // 2]
data2 = data[num_elements // 2:]

# Declaring index
p = hnswlib.Index(space='cosine', dim=dim)  # possible options are l2, cosine or ip
p.init_index(max_elements=num_elements//2, ef_construction=100, M=26)
p.set_ef(10)
p.set_num_threads(2)
p.add_items(data1)

p.save_index('part1.bin')

``` 
Then I used `sys.getsizeof(p)` and I got 52bytes. That is unreal. Secondly by checking the size of `part1.bin`, it gives me `40MB`. So  in that sense, if I make batches and save every structure like this, 

1. How can I search from these parts?
2. How much memory would it exactly take?

**Comment by yurymalkov** [comment]
Hi @deshwalmahesh,
I am not sure. Are you talking about ram or disk?

**Comment by deshwalmahesh** [comment]
I'm talking about RAM. index has to be in memory at the server side to give the results. right?

**Comment by yurymalkov** [comment]
RAM consumption after the index is created is roughly: the size of the data (4*D*N for float32) + size of the links (~ 2*M*N)+some overhead that depends on the number of threads (say, 20-30%).
And as the code is done in C++ there is not easy way to measure the RAM consumption without modifying the code.

Note that when you call add_items(data1) you will have two copies of your data (one in data1 and another in the index), so for large indices you would like to load data in small portions (e.g. load 1Mb add to index, load another 1Mb ...)
