### ISSUE TITLE
C++ Inner product on normalised vectors return >1 value

### ISSUE THREAD

**Issue by danwanban** [nmslib/hnswlib#301]
Hi,

I'm using the c++ interface. I'm normalising the vectors before adding them to the HSNW.
The HSNW is using the InnerProductSpace.
When I query, I get results with the first measure (q=HNSW->searchKnn(...); q.top().first)  bigger than 1.

What am I missing ? 

Thanks for the help !

**Comment by yurymalkov** [comment]
Hi @danwanban , if you normalize the data that should not happen. 
I would compute it manually and compare to the output of the algorithm.

**Comment by danwanban** [comment]
Thanks !
