### ISSUE TITLE
save_index() and load_index() method bad interaction with certain properties

### ISSUE THREAD

**Issue by ShuAiii** [nmslib/hnswlib#316]
Some properties don't seem to be getting set correctly by `load_index()` after being saved by `save_index().` I wonder if the new index will function correctly (with the original M or ef_construction values even through displaying 0).

Please see below the properties `ef_construction`, `element_count` and `M` not being set correctly.

```
>>> knn = hnswlib.Index("l2", 10)
>>> knn.init_index(max_elements=1000, ef_construction = 200, M = 16, random_seed = 100)
>>> knn.add_items(data, num_threads=1)
>>> knn.save_index("knn.bin")
>>> new_knn = hnswlib.Index(space='l2', dim=10)
>>> new_knn.load_index("knn.bin", max_elements = 1000)
>>> knn.get_items(knn.get_ids_list())
[[1.0, 23.0, 4.0, 5.0, 6.0, 432.0, 3.0, 4.0, 5.0, 6.0]]
>>> new_knn.get_items(new_knn.get_ids_list())
[[1.0, 23.0, 4.0, 5.0, 6.0, 432.0, 3.0, 4.0, 5.0, 6.0]]
>>> knn.M
16
>>> new_knn.M
0
>>> knn.ef_construction
200
>>> new_knn.ef_construction
0
>>> knn.space
'l2'
>>> new_knn.space
'l2'
>>> knn.dim
10
>>> new_knn.dim
10
>>> knn.element_count
1
>>> new_knn.element_count
0
>>> knn.ef
10
>>> new_knn.ef
10
```

**Comment by yurymalkov** [comment]
@ShuAiii Thank you! That is reproducible. Will debug it.

**Comment by ShuAiii** [comment]
@yurymalkov Thanks! Can you please confirm this only a display bug and does not affect the functionality of the index?

**Comment by ShuAiii** [comment]
Thank you! Will close the issue

**Comment by yurymalkov** [comment]
Thanks again for reporting this!

**Comment by DmitryKey** [comment]
are you guys planning a release for this at some point? I'm seeing the same "reset" of M / ef_construction, but I trust this is only presentation issue -- thanks for confirming.

**Comment by yurymalkov** [comment]
Hi @DmitryKey, I'll merge it soon.

**Comment by DmitryKey** [comment]
thanks @yurymalkov Great library otherwise!

**Comment by yurymalkov** [comment]
@DmitryKey it should be in the latest release.

**Comment by DmitryKey** [comment]
cool, appreciate quick release @yurymalkov
