### ISSUE TITLE
Question: How does using multiple cores in parallel work?

### ISSUE THREAD

**Issue by Addyvan** [nmslib/hnswlib#333]
Is there support for using multiple cores similar to being able to set the number of threads?

**Comment by yurymalkov** [comment]
Hi @Addyvan I am not sure I am following the difference between cores (hardware object) and threads (software object). 
hnswlib is using cores and that is controlled by the number of threads.

**Comment by Addyvan** [comment]
Makes sense, could have investigated a little further myself. Thanks @yurymalkov
