### ISSUE TITLE
semantic_search_quora_hnswlib get error "wrong dimensionality of the vectors"

### ISSUE THREAD

**Issue by snakecy** [nmslib/hnswlib#337]
```bash
python semantic_search_quora_hnswlib.py
```

error is :

Start creating HNSWLIB index
Traceback (most recent call last):
  File "semantic_search_quora_hnswlib.py", line 83, in <module>
    index.add_items(corpus_embeddings, list(range(len(corpus_embeddings))))
RuntimeError: wrong dimensionality of the vectors

**Comment by yurymalkov** [comment]
It seems like that is an external error in the ` semantic_search_quora_hnswlib.py` which is not a part of hnswlib
