### ISSUE TITLE
RuntimeError: Not enough memory

### ISSUE THREAD

**Issue by Raghuram1656** [nmslib/hnswlib#354]
Hi Team,

I am getting RuntimeError: Not enough memory when my max_corpus_size  = 2595491. 

Could you please let me know if any solution for this.  

Thanks,
Siva Raghuram Susarla.

<img width="788" alt="2021-12-15_9-42-39" src="https://user-images.githubusercontent.com/11694110/146122088-e9adb913-46fa-4213-8820-11790b0525fb.png">

**Comment by yurymalkov** [comment]
Hi @Raghuram1656,
It seems there is not enough RAM on the machine. Can you check how much do you have?

**Comment by Raghuram1656** [comment]
Thank you. I tried on Big memory machine and problem solved.
