### ISSUE TITLE
save_index() and load_index() not saving ef parameter

### ISSUE THREAD

**Issue by rogeriochaves** [nmslib/hnswlib#358]
I guess this bug probably have the same reason as #316, when I load a saved index the ef property gets reset:

```python
>>> import hnswlib
>>> knn = hnswlib.Index("cosine", 10)
>>> knn.init_index(max_elements=1000, ef_construction = 200, M = 16, random_seed = 100)
>>> knn.ef
10
>>> knn.set_ef(100)
>>> knn.ef
100
>>> knn.save_index("knn.bin")
>>> new_knn = hnswlib.Index(space='cosine', dim=10)
>>> new_knn.load_index("knn.bin", max_elements = 1000)
>>> new_knn.ef
10
```

**Comment by yurymalkov** [comment]
Hi @rogeriochaves, ef is not stored in the file (this is mentioned in readme in `set_ef`). Historically ef was considered a runtime parameter, adding it now will cause backward incompatibility. 

Index _pickling_ is an alternative which stores the ef parameter as opposed to saving the index.

**Comment by rogeriochaves** [comment]
Thank you for the clarification, for me it's good enough to just set the ef again after loading the model, it was just unexpected since other parameters are saved, others might be tricked by that as well. But cool, will close this then, thanks!
