### ISSUE TITLE
How to avoid save whole index after add_items

### ISSUE THREAD

**Issue by ssssssssssss** [nmslib/hnswlib#36]
We are using this lib to save about 10000+ indexes which results in a ~ 1GB index file. As we are adding new items continuously, we'd like to know if there are some optimizations can be done to avoid saving the whole index which takes a long time.

**Comment by yurymalkov** [comment]
Hi @ssssssssssss ,

Sure, this can be done, though it probably will break backwards compatibility in some way or another. Either it ill break old saved indexes (extra variable) or you would have to specify the max number of elements during load and always save only non-zero elements (seems to be a better solution, but old code will need to be updated to account for this).

**Comment by yurymalkov** [comment]
I can do this in a week or two.

**Comment by ssssssssssss** [comment]
Thanks. Compatibility may be an issue, but I think it's the right direction to be part of a real running product.
