### ISSUE TITLE
New release to include AVX runtime check

### ISSUE THREAD

**Issue by yihming** [nmslib/hnswlib#365]
Hi @yurymalkov ,

As PR #357 has been merged, may I ask for a new release of hnswlib which includes it ASAP? This will help us resolve its conda version issue https://github.com/conda-forge/hnswlib-feedstock/pull/11.

Many thanks!

Sincerely,
Yiming

**Comment by yurymalkov** [comment]
Hi @yihming, ok, I'll make a release this week (need to run manual checks).

**Comment by yihming** [comment]
Many thanks!

**Comment by yurymalkov** [comment]
Released
