### ISSUE TITLE
A question about topk

### ISSUE THREAD

**Issue by yiwc** [nmslib/hnswlib#381]
if A uses knn query topk=100, in another case, B use topk=500, and selects top 100 out of 500.

Are two cases the same? or B might have a better result?

**Comment by yurymalkov** [comment]
Hi @yiwc.
Internally the algorithm collects `ef` neighbors and returns first `K` of the best elements. So if `ef`>`K` then it should be exactly the same thing both in terms of runtime and result

**Comment by yiwc** [comment]
Thanks @yurymalkov ,

I see, It makes sense. 

So I guess if ef<K, then the result could be different, and case B should have better result than A, am I right？

**Comment by yurymalkov** [comment]
Hi @yiwc , yes, correct. Also it will be slower

**Comment by yiwc** [comment]
closed with thanks!
