### ISSUE TITLE
resizing incremental index

### ISSUE THREAD

**Issue by lzuwei** [nmslib/hnswlib#39]
It seems that when creating an index we need to specify the number of elements it holds. I have a few questions related to this.

1) If we add entries to more than the number of elements specified, what would happen?
2) Is it possible to auto expand the allocated index size when it reaches a threshold eg: 75% of max

**Comment by yurymalkov** [comment]
Hi @lzuwei ,
1. It would now throw an exception.
2. It is not implemented at the moment. Manual expansion will be added soon (hopefully next weekend) via saving/loading of the index (this would allow avoiding doubling the memory consumption during the expansion moment). Pool requests for the auto expansion are welcome.

**Comment by yurymalkov** [comment]
@lzuwei Yes, it will be exposed.

**Comment by yurymalkov** [comment]
@lzuwei I've added support for index resizing via saving/loading. Please see the updated example https://github.com/nmslib/hnsw/blob/master/examples/example.py

**Comment by lzuwei** [comment]
Thank you! I will take a look at it!
