### ISSUE TITLE
efConstruction and M

### ISSUE THREAD

**Issue by ljn-aaa** [nmslib/hnswlib#392]
Thanks for great work！

In the paper, to find the neighbors of each node, you need to first find efConstruction candidate neighbors by SEARCH_LAYER function. Then find M neighbors among the candidate neighbors for connection by SELECT_NEIGHBORS_HEURISTIC function. So you need efConstruction to be always greater than M. But why in the experiment, your ef Construction appears to be less than M.

**Comment by ljn-aaa** [comment]
When efContrcution is less than M, how is it finding neighbors

**Comment by yurymalkov** [comment]
Hi @ljn-aaa. `ef_costruction` cannot be lower than `M`. It is enforced in the code https://github.com/nmslib/hnswlib/blob/443d667478fddf1e13f2e06b1da4e1ec3a9fe716/hnswlib/hnswalg.h#L38

**Comment by ljn-aaa** [comment]
Thanks for your reply！
