### ISSUE TITLE
load existing/pre-built database/graph and insert new elements

### ISSUE THREAD

**Issue by jianshu93** [nmslib/hnswlib#398]
Hello Hnswlib developers,

I am in a situation where building is quite expensive (a self-provided metric distance function related to minhash based Jaccard distance of genomic sequences) but database is large and update very often. Is there a way to load the existing database/graph and then insert new database elements to it, assume that we know the new elements are not the same with any elements that are already in the loaded database/graph. The same graph constructing parameters should be used and whether the new elements to be inserted is the same with existing ones should also be checked. It seems this will be quite useful for some applications.

Does this sounds/make sense to you?

Thanks,

Jianshu

**Comment by yurymalkov** [comment]
Hey @jianshu93, I am not sure I fully understood. The current functionality allows graphs to be saved/loaded, and new elements can be inserted (and existing ones updated, though it is more costly).

**Comment by jianshu93** [comment]
Thanks. I missed that part.

**Comment by jianshu93** [comment]
Hello Malkov,

By the way, there is a beautiful reimplementation in Rust here: https://github.com/jean-pierreBoth/hnswlib-rs
I do not see a Rust version on the intro page but a lot of others such as GO, java et.al. The beauty of it is that it is both memory and thread safe. I think it worths a mention on you main page.

Thanks,

Jianshu

**Comment by yurymalkov** [comment]
Ok. Feel free to add to the main page. I can add it later as well .
