### ISSUE TITLE
Error installing hnswlib

### ISSUE THREAD

**Issue by REH2022** [nmslib/hnswlib#403]
[Failed pip install hnswlib.pdf](https://github.com/nmslib/hnswlib/files/9384078/Failed.pip.install.hnswlib.pdf)
[Failed pip3 install hnswlib.pdf](https://github.com/nmslib/hnswlib/files/9384080/Failed.pip3.install.hnswlib.pdf)
I'm having trouble installing hnswlib. I'm currently running on MacOS Big Sur version 11.6.8 and using 
Apple clang version 13.0.0 (clang-1300.0.29.30), Target: x86_64-apple-darwin20.6.0, Thread model: posix. 
Would greatly appreciate guidance on installing hnswlib. Thanks!

**Comment by yurymalkov** [comment]
Hi @REH2022 
Hm. Can you try run `export  HNSWLIB_NO_NATIVE=1` before the pip install?

**Comment by REH2022** [comment]
That worked. Thank you so much!

**Comment by gitgithan** [comment]
Any other solutions to this? 
I got the same error on Mac Big Sur Version 11.3 and Apple clang version 12.0.5

**Comment by REH2022** [comment]
I'm actually now having the same issue again. I recently updated my laptop software to macOS Big Sur Version 11.7.4 and have the following:
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

I tried the following like last time, but it's no longer working. 
export  HNSWLIB_NO_NATIVE=1 
pip3 install hnswlib

In R, I'm now getting the following error:
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml): started
  Building wheel for hnswlib (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/wc
      creating var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp
      creating var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/rehamlin/.virtualenvs/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/tmp97mv7u5e.cpp -o var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/tmp97mv7u5e.o -std=c++14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/rehamlin/.virtualenvs/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/tmp5xoc_e94.cpp -o var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/tmp5xoc_e94.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-310
      creating build/temp.macosx-10.9-universal2-cpython-310/python_bindings
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/pip-build-env-qd50q_xx/overlay/lib/python3.10/site-packages/pybind11/include -I/private/var/folders/wc/y80vlkjd3jjcglr9chdy9s6c0000gp/T/pip-build-env-qd50q_xx/overlay/lib/python3.10/site-packages/numpy/core/include -I./hnswlib/ -I/Users/rehamlin/.virtualenvs/venv/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-310/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.0\" -std=c++14 -fvisibility=hidden
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
Error: Error installing package(s): "'hnswlib'"

Thanks in advance for your help.
