### ISSUE TITLE
Recall degrade when increasing search_ef

### ISSUE THREAD

**Issue by patelprateek** [nmslib/hnswlib#423]
I was running some basic sanity checks around reproducibility of results , index and ran into few issues which is a bit surprising to me . Wanted to understand if this is expected and possible explanation or hypothesis

Test case : 100K 128 dimensional embedding , each dimension is a uniform random float within [min, max] range.  similarly generated 10k random queries . note : Queries are not sampled from data that is indexed but generated separately 

Create hnsw graph (hnsw_original) using data and generated top100 result for each query (single thread)
Create another hnsw graph (hnsw_v2) (same construction params indexing_ef = 200 , M =32 , search_ef=128), same data , same queries and compared the topk results 

I observe 99 % recall when search_ef = 128 , recall here means the intersection of the two topk results / 100 ;
when increased search_ef = 256, 512  when querying the second graph the recall actually degrades to 90%, 84% , this is surprising as i assume larger search_ef would mean more candidates compared and more optimal result ? 

overall recall = average_recall_over_10k_queries 
recall for single query = intersection (top100 from hnsw_original , top100 from hnsw_v2) / 100 

similarly if i create hnsw graphs using multiple threads  , the recall drops 95% for search_ef =128 and similarly degrades on increasing search_ef.

so the 2 issues are 
1) single threaded vs multi-threaded building of index with same data leads to slight recall degradation : 99% vs 94% (1 thread vs 12 or more threads) 
2) increasing search_ef (in both single and multi threaded cases) causing recall degradation  (recall droping from 99% to 94% dropping further to 90% when search_ef increased from 128 to 256 to 512 when queryin hnsw_v2)

Any idea what could possibly be going on ?

**Comment by YiJustin401** [comment]
Hello, I'm also facing the same problem. How did you solve it
