### ISSUE TITLE
25% speedup after uncommenting prefetch instruction

### ISSUE THREAD

**Issue by greghvk** [nmslib/hnswlib#437]
Hi,
I uncommented this line and saw some performance improvement when benchmarking dot product calculation (25% speedup):
https://github.com/nmslib/hnswlib/blob/359b2ba87358224963986f709e593d799064ace6/hnswlib/space_l2.h#L111
Is there maybe a reason that this is commented that I'm not aware of, before I pursue this issue and create more test/benchmarks?

**Comment by yurymalkov** [comment]
I think it didn't help in the experiments, so we commented it.
Can you share the setup (data, hardware) where is helped?
