### ISSUE TITLE
reordering warning with g++ in HierarchicalNSW

### ISSUE THREAD

**Issue by jlmelville** [nmslib/hnswlib#438]
The initializer in the third constructor for `HierarchicalNSW` has `label_op_locks_` and `link_list_locks_(max_elements)` initialized in a different order to their declaration (on line 42 and 39, respectively):

https://github.com/nmslib/hnswlib/blob/359b2ba87358224963986f709e593d799064ace6/hnswlib/hnswalg.h#L95-L96

This causes a `-Wreorder` warning to be emitted by g++. Not a big deal admittedly, but I was hoping to finally get the R bindings up to date, and a compiler warning will be grounds for rejection by CRAN (not anyone's problem but mine).

Happy to provide a PR, although the fix is as trivial as swapping the position of the two initializers.

**Comment by yurymalkov** [comment]
Hi @jlmelville, sorry for the long response. 
Yeah, a PR would be welcomed! Thanks!
