### ISSUE TITLE
hnsw index space complexity

### ISSUE THREAD

**Issue by jianshu93** [nmslib/hnswlib#445]
Hello Team,

What is the theoretical space complexity of hnsw index with respect to the number of data point (N), I cannot find it out in the paper, I feel like it is some how linear related to N or something.

Thanks,

Jianshu

**Comment by yurymalkov** [comment]
Hi @jianshu93 
The theoretical expected complexity is O(N) in the limit of large N (assuming some stuff like that the graph is similar to true Delaunay graph), similar to skiplist.

**Comment by jianshu93** [comment]
Hello @yurymalkov ,

Thanks for the response, I read that in another paper (https://dl.acm.org/doi/abs/10.14778/3489496.3489506?casa_token=1qCegb6AsSgAAAAA:bvML9hjPlwZ8aUxEUHxsgrLSRU-iQ1WjZ8ht8A31tifz8Oa4oEZ6-wowAoroaX2Kw5becyR8EQYz), it was <img src="https://render.githubusercontent.com/render/math?math=(1+\tau)*N*d">, where \tau << 1 and d is the dimension.

**Comment by yurymalkov** [comment]
Ok. I am not sure about this formula actually, but the _N_ part is correct.
