### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by greengeckowizard** [nmslib/hnswlib#462]
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block" indicates that there is not enough memory available to allocate a static TLS block for the `hnswlib` module.

I'm running this in a docker container and I receive this error.

**Comment by greengeckowizard** [comment]
I tried running this inside the container "export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1" and that didn't fix it.

**Comment by wendyliga** [comment]
@greengeckowizard what did you do to solve this?
