### ISSUE TITLE
Usage of built index across different CPU arch

### ISSUE THREAD

**Issue by wilsonzlin** [nmslib/hnswlib#496]
Thanks for this great library. I'm curious if there's any limitation or issues if I build an index on, say, aarch64, save it somewhere using the standard `save_index` method, and then load it on an x86_64 machine and query the index from there? Is the index format machine-independent? I'm using the standard Python bindings library.

**Comment by yurymalkov** [comment]
Sorry for a very late reply.
The index might be dependent on little endian vs big endian encoding. Other than that there should be no difference.
As far as I understand both x86_64 and typical arch architecture are both little endian, so they should be compatible

**Comment by wilsonzlin** [comment]
Awesome, thanks for the update. If endianness is the only concern then it should be OK; as you pointed out, x86_64 and aarch64 should both be little endian.
