### ISSUE TITLE
Memory leak found for python lib

### ISSUE THREAD

**Issue by kasim-du** [nmslib/hnswlib#50]
I find there is a memory leak when loading the index file. Here are the code snippets.
//python3
import psutil
import hnswlib

proc = psutil.Process()
index_map = {}
for i in range(100):
        print('before: {} MB'.format(proc.memory_info().rss / 1024 / 1024))
        knn_index = HNSWIndex(128, 10000)
        knn_index.load('resources/indexes/03fef96d.runscope_medium.1636638189768806400.idx')
        index_map['ks1'] = knn_index
        print('after: {} MB'.format(proc.memory_info().rss / 1024 / 1024))

//output
before: 14.484375 MB
after: 23.72265625 MB
before: 23.72265625 MB
after: 24.390625 MB
before: 24.390625 MB
after: 24.92578125 MB
before: 24.92578125 MB
after: 33.6875 MB
before: 33.6875 MB
after: 41.6796875 MB
before: 41.6796875 MB
after: 49.4140625 MB
before: 49.4140625 MB
after: 57.40625 MB
before: 57.40625 MB
after: 65.140625 MB
before: 65.140625 MB
...

**Comment by yurymalkov** [comment]
@kasim-du Thanks for reporting! I'll fix it very soon.

**Comment by yurymalkov** [comment]
Should be fixed in https://github.com/nmslib/hnsw/tree/fix-multiply-loads , although I haven't tested it directly.
The branch will be merged after a while.

**Comment by kasim-du** [comment]
Thanks for your fix, but there are still memory usage increase for the second and forth load of the same index file.
//output
before: 14.5078125 MB
after: 23.3203125 MB
before: 23.3203125 MB
after: 24.05859375 MB
before: 24.05859375 MB
after: 24.05078125 MB
before: 24.05078125 MB
after: 31.78125 MB
before: 31.78125 MB
after: 31.78125 MB
before: 31.78125 MB
after: 31.78125 MB
before: 31.78125 MB
after: 31.78125 MB
...

**Comment by yurymalkov** [comment]
@kasim-du I am not sure if this a bug. Might be some sophisticated compiler memory management optimization.
