### ISSUE TITLE
load successed on arm64-v8a,but faild on armeabi-v7a,why?

### ISSUE THREAD

**Issue by WellWang-S** [nmslib/hnswlib#516]
abort_message:
assertion “terminating with uncaught exception of type std::runtime_error: Index seems
be corrupted or unsupported" failed

**Comment by yurymalkov** [comment]
Hi @WellWang-S ,

I think the main reason is that armeabi-v7a is 32-bit, so `size_t` is 4 bytes instead of the 8. I guess that can be hacked by changing the the types from `size_t` to `long long` or something in https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L22C7-L53

**Comment by WellWang-S** [comment]
> Hi @WellWang-S ,
> 
> I think the main reason is that armeabi-v7a is 32-bit, so `size_t` is 4 bytes instead of the 8. I guess that can be hacked by changing the the types from `size_t` to `long long` or something in https://github.com/nmslib/hnswlib/blob/master/hnswlib/hnswalg.h#L22C7-L53

thanks
