### ISSUE TITLE
HNSW package for bun

### ISSUE THREAD

**Issue by KaKashi1210** [nmslib/hnswlib#533]
![image](https://github.com/nmslib/hnswlib/assets/97914006/d02e103d-d43c-4bd4-af8a-799339f9aa09)

it works perfectly with node but would be great if the support for bun is available

**Comment by yurymalkov** [comment]
Hi @KaKashi1210 

This is the repo for C++/python package. I think you are referring to something else.

**Comment by KaKashi1210** [comment]
ohh, my bad sorry for inconvenience
