### ISSUE TITLE
Renaming repository to hnswlib

### ISSUE THREAD

**Issue by yurymalkov** [nmslib/hnswlib#55]
Probably, the repository should be renamed to hnswlib (python lib's name). 
Note sure if there any cons for that.

**Comment by dnbaker** [comment]
It is confusing for the repository to be 'hnsw' when the same abbreviation is used for the Hierarchical Small World Networks method that nmslib provides.

**Comment by yurymalkov** [comment]
If there are no concerns, I'll rename the repository hnswlib after the weekend.

**Comment by searchivarius** [comment]
Please, let me know when you are done. I just realized that we don't have a link to the HNSWLIB repository from the main NMSLIB README, so I will add it.

**Comment by yurymalkov** [comment]
@searchivarius just renamed it

**Comment by searchivarius** [comment]
done thanks!
