### ISSUE TITLE
The IP space [1.0 - sum(AiBi)] might be inaccurate. Why not separate the IP from the cosine, and define the IP simply as [- sum(AiBi)]?

### ISSUE THREAD

**Issue by Arthur-Bi** [nmslib/hnswlib#554]
I understand that define Ip as [1.0 - sum(Ai*Bi)] is really convenient for calculating Cosine similarity. But this might cause in-accuracy when calculating IP. I checked faiss and milvus, they donnot have **1.0 -**

**Comment by yurymalkov** [comment]
Hm. Why that would inaccurate? I can imagine it to make a difference only if values of - sum(AiBi) are very close to zero = orthogonal vectors, which seems to be very uncommmon
