### ISSUE TITLE
Normalization of CLIP Vectors Before Storing in Milvus for Cosine Similarity

### ISSUE THREAD

**Issue by Bruc3Stark** [nmslib/hnswlib#557]
After vectors are transformed by the CLIP model, do they need to be normalized before being stored in Milvus? If they are stored in the database without normalization, will it affect the results when calculating cosine similarity?

**Comment by yurymalkov** [comment]
No, it should affect it if you use cosine. I am not totally sure about milvus, but this is the case for hnswlib
