### ISSUE TITLE
Is simultaneous querying and inserting thread-safe?

### ISSUE THREAD

**Issue by wangdehu** [nmslib/hnswlib#562]
I notice https://github.com/nmslib/hnswlib/issues/100. Has the situation changed in this regard since this time?
Is simultaneous querying and inserting thread-safe?

Thanks

**Comment by yurymalkov** [comment]
Hi @wangdehu . Unfortunately, it is still not thread-safe.

**Comment by wangdehu** [comment]
Thanks a lot for your response.
