### ISSUE TITLE
Why called `ef`? 

### ISSUE THREAD

**Issue by gitfourteen** [nmslib/hnswlib#593]
Really feel bothering to call a critical parameter something like `ef` without knowing its literal meaning or its acronym.

**Comment by gitfourteen** [comment]
Finally, find someone do [a decent patch-work](https://docs.oracle.com/en/database/oracle/oracle-database/23/vecse/understand-hierarchical-navigable-small-world-indexes.html): `EF` stands for `Enter Factor`. Relieved.

**Comment by yurymalkov** [comment]
Hi @gitfourteen, 
Sorry for a late reply. `ef` initially meant "ensure factor", which meant this parameter ensures the high recall, but was grammatically incorrect.
