### ISSUE TITLE
Possible `linkLists_[i]` out-of-bounds reads

### ISSUE THREAD

**Issue by wilsonzlin** [nmslib/hnswlib#595]
While porting parts of the code to Rust to parse and extract a disk-saved hnswlib index, I found some unexpected panics in the equivalent Rust code of this section in `searchKnn`:

```cpp
for (int level = maxlevel_; level > 0; level--) {
    // ...
   data = (unsigned int *) get_linklist(currObj, level);
   int size = getListCount(data);

   tableint *datal = (tableint *) (data + 1);
   for (int i = 0; i < size; i++) {
     tableint cand = datal[i];
     // ...
  }
}
```

Where `get_linklist` and `getListCount` are defined as follows:

```cpp
linklistsizeint *get_linklist(tableint internal_id, int level) const {
  return (linklistsizeint *) (linkLists_[internal_id] + (level - 1) * size_links_per_element_);
 }

unsigned short int getListCount(linklistsizeint * ptr) const {
  return *((unsigned short int *)ptr);
}
```

In Rust, when reading the [`linkLists_[i]`](https://github.com/nmslib/hnswlib/blob/c1b9b79af3d10c6ee7b5d0afa1ce851ae975254c/hnswlib/hnswalg.h#L805) from disk, I use a Rust Vec<u8> as the equivalent to the raw `char*`, so for `get_linklist` I slice the `linkLists_[i]` Vec at offset `(level - 1) * self.size_links_per_element_)` as I presume that's the equivalent to the C++ above. However, this is often out of bounds. Is the C++ code doing an unchecked out-of-bounds read (i.e. adding to the `linkLists_[internal_id]` pointer beyond the length `malloc`ed)? It's possible I've misread or overlooked some of the source C++, so wanted to raise here first before I dived deeper.

**Comment by jianshu93** [comment]
hi @wilsonzlin, why not use the Rust implementation here:https://github.com/jean-pierreBoth/hnswlib-rs, also mentioned in the home page. 

Thanks,
Jianshu

**Comment by wilsonzlin** [comment]
I currently don't need the algorithm itself, I'm doing some research on properties of the hnswlib-built graph, so I've copied a small amount of code over to load the data from disk in Rust. Although thanks for the pointer, might be useful once I do need to compare implementations in Rust down the road.

**Comment by wilsonzlin** [comment]
I think it works because the traversal starts at the highest level node and always finds a node at or above the same level, so max_level is always in bounds.
