### ISSUE TITLE
How to get items by ids

### ISSUE THREAD

**Issue by Imagist-Shuo** [nmslib/hnswlib#72]
Hi @yurymalkov & @searchivarius,

I have used the python version to build index of some items with ids and stored it into a file. Now I have a question that is there a method to get the items by their assigned ids after I load the index file?

Thanks,
Shuo

**Comment by Imagist-Shuo** [comment]
Awesome, thanks for your reply! Looking forward to this new feature. It will save me a lot.

Best,
Shuo

**Comment by yurymalkov** [comment]
@Imagist-Shuo Finally I found some time to add this functionality

**Comment by realsergii** [comment]
Hi @yurymalkov, this method crashes on my system (OS X 10.13.6)

Python 3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
>>> import hnswlib
>>> import numpy as np
>>> p = hnswlib.Index(space='l2', dim=512)
>>> p.init_index(max_elements = 10000, ef_construction = 200, M = 80)
>>> a = np.zeros(shape=(1,512))
>>> p.set_ef(200)
>>> p.add_items(a, 1)
>>> p.get_items(1)
Segmentation fault: 11

**Comment by yurymalkov** [comment]
Hi @realsergii 

The problem with a snippet is that labels also have be passed as an array.
So:
```python
import hnswlib
import numpy as np
p = hnswlib.Index(space='l2', dim=512)
p.init_index(max_elements = 10000, ef_construction = 200, M = 80)
a = np.zeros(shape=(1,512))
p.set_ef(200)
p.add_items(a, [1])
p.get_items([1])
```
returns the zero array
