### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by scottgigante** [nmslib/hnswlib#75]
As far as I can tell hnswlib can be installed with `pip` by running

```
pip install --user git+https://github.com/nmslib/hnswlib#subdirectory=python_bindings
```

but it would be nice to add it as a regular dependency via PyPi. Do you have plans to publish it there?

**Comment by scottgigante** [comment]
@yurymalkov what kind of help do you need? I don't have a lot of bandwidth but it's just related to packaging I'm more than happy to assist.

**Comment by yurymalkov** [comment]
@scottgigante I would be nice if you have time to help with packaging. E.g. point out a good step-by-step guide.

**Comment by scottgigante** [comment]
@yurymalkov if you want to upload it in its current form I think you could just do
```
cd hnswlib/python_bindings
python setup.py sdist bdist_wheel
twine upload -r pypi dist/*
```
If you've never used `twine` before, you will have to open an account on pypi.org and test.pypi.org, download [twine](http://pypi.org/project/twine) and create your `~/.pypirc` as follows:

```
[distutils]
index-servers =
  pypi
  pypitest

[pypi]
repository=https://upload.pypi.org/legacy/
username=myuser
password=mypassword

[pypitest]
repository=https://test.pypi.org/legacy/
username=myuser
password=mypassword
```

Read more: https://packaging.python.org/guides/using-testpypi/

**Comment by yurymalkov** [comment]
@scottgigante Thank you!

**Comment by louisabraham** [comment]
@scottgigante I don't think it is so simple because of the `#include "../hnswlib/hnswlib.h"`.

I am willing to help. There are two solutions:

- changing the structure of the git folder
- calling cp when wanting to publish a new version on pypi

Which one do you prefer @yurymalkov?

**Comment by yurymalkov** [comment]
@scottgigante Thank you so much!
I think the second option is a bit better (keeps backward compatibility).
