### ISSUE TITLE
negative cosine similatiry

### ISSUE THREAD

**Issue by vinnitu** [nmslib/hnswlib#76]
I get negative distance for item with index 0.
It must be 0, but returned -1.1920928955078125e-7 for item itself
How to handle it?

seems it linked to https://github.com/nmslib/hnswlib/issues/34

**Comment by yurymalkov** [comment]
@vinnitu this seems to be due to finite precision of 32-bit floats during distance computations.
float32 has around 7 decimal digits (this explains the 1e-7 error).
Does it pose a problem in your application?

**Comment by yurymalkov** [comment]
@preetim96 Can you give a sample script so I could look into the problem?

**Comment by preetim96** [comment]
@yurymalkov 
I did everything similar to the code provided at the hnsw's github page.
My data contain 5 Million documents, each having array of length 3000.

I think the problem arises because of my mistake, I was indexing data in 'cosine' space. But while using I was loading it in 'l2' space.

But indexing and loading data in same space solved my problem

**Comment by yurymalkov** [comment]
@preetim96 Got it. Thanks!

**Comment by xiaozhuka** [comment]
I have meet negtative distance in cosine too. Does it need to normalize the data first when input to the hnsw?

**Comment by yurymalkov** [comment]
Hi @xiaozhuka, no you do not need to normalize if you use cosine similarity space (`'cosine'`).

**Comment by yurymalkov** [comment]
This seems to be caused by using wrong space (i.e. euclid vs cosine)

**Comment by Simplesss** [comment]
How to measure cosine similarity in hnsw? When I use l2 distance, the result is not ideal, so I want to write a cosine distance metric, but I always report an error, can you provide a cosine similarity measure to build the hnsw model？

**Comment by alejandrojcastaneira** [comment]
Hello everyone,

I'm creating and loading my index using "cosine" as distance, and I'm also getting negative distance values, usually the first 1 to 3 results. 

Consequently, the final order of the results is incorrect.
