### ISSUE TITLE
Missing call to addPoint for python bindings?

### ISSUE THREAD

**Issue by rafael-aero** [nmslib/hnswlib#8]
@yurymalkov Awesome code, really enjoying it compared to the other similar libraries. 

Just one remark I noticed here, it seems that the python bindings provided are not actually adding any vector to the index - there is [no call to addPoint on the code](https://github.com/nmslib/hnsw/blob/5cde7785f3a09508a3a916b2f8c4b03f9641cb41/python_bindings/bindings.cpp#L190):

```
if(normalize==false) {
    ParallelFor(start, rows, num_threads, [&](size_t row, size_t threadId) {
        size_t id = ids.size() ? ids.at(row) : (cur_l+row);
    });
} else{
    std::vector<float> norm_array(num_threads * dim);
    ParallelFor(start, rows, num_threads, [&](size_t row, size_t threadId) {
        // normalize vector:
        size_t start_idx = threadId * dim;
        normalize_vector((float *) items.data(row), (norm_array.data()+start_idx));

        size_t id = ids.size() ? ids.at(row) : (cur_l+row);
    });
};


```

Also, one question. Is the library supposed to be thread safe for adding new items? Or just for performing search?

**Comment by yurymalkov** [comment]
Thanks! I definitely need to set up Travis 😃 

Adding new items should be thread safe, i.e. can be done with python threads in parallel. I have not tested it yet, but if there is a problem - it is in python bindings part (C++ code is well tested).

However, adding and searching simultaneously should not be thread safe now. This was done intentionally to reduce the locks (which might slow down the search), assuming that user does not run insertions during the search.
I am considering adding a separate fully thread safe search method. Please let me know if it is interesting.

**Comment by tlyalex** [comment]
"I am considering adding a separate fully thread safe search method. Please let me know if it is interesting." Is there any update on this one? It would be a very useful feature if add and search could be fully threadsafe with each other.

**Comment by yurymalkov** [comment]
@tlyalex Not much has changed, as there is not much ask. After merging #216 I can look into that.
