### ISSUE TITLE
gcc UBSan runtime error: load of misaligned address

### ISSUE THREAD

**Issue by jlmelville** [nmslib/hnswlib#87]
I was testing the R bindings to hnswlib using the GCC UBSan support in [rhub](https://builder.r-hub.io/status/RcppHNSW_0.1.0.tar.gz-1eb94b7ad76845aeaf913a65c9552d07) and the following runtime error is reported:
```
../inst/include/hnswalg.h:142:112: runtime error: load of misaligned address 0x55bc6b4768fc for type 'labeltype', which requires 8 byte alignment
0x55bc6b4768fc: note: pointer points here
  cd cc 4c 3e 02 00 00 00  00 00 00 00 09 00 00 00  00 00 00 00 02 00 00 00  01 00 00 00 04 00 00 00
```
I add a macro for error reporting to `hnswalg.h` so the line number is a bit off. It's referring to:

https://github.com/nmslib/hnswlib/blob/79c4ba49ae55afaef1e37bb52490e06d48c2d7ca/hnswlib/hnswalg.h#L135

My limited understanding of this error is that `memcpy` should be the preferred way of dealing with this rather than casting. 

I am entirely unsure of the significance or validity of this, but I thought I would pass it on in case it's of interest.

**Comment by yurymalkov** [comment]
Hi @jlmelville,

Many thanks for reporting the issue! 

I agree, it is worth to change casting to ```memcpy```. I'll check if it affects the performance, and if it is ok will update the master.

**Comment by yurymalkov** [comment]
Hi @jlmelville! I have merged the fix to ```develop``` branch. 
Can you check that it solves the problem?

**Comment by jlmelville** [comment]
Yes, that seems to have solved it. I no longer see that error in rhub.

**Comment by jlmelville** [comment]
Thanks for fixing, @yurymalkov! Closing.
