### ISSUE TITLE
Paginate KNN query result from index

### ISSUE THREAD

**Issue by OElesin** [nmslib/hnswlib#91]
Having added items to my index and being able to query the index to get results. I want to know if it is possible to load results from index incrementally. E.g. by distance to centroid.

e.g:
```python
labels, distances = p.knn_query(d, k =1, end =50)
print labels, distances

labels, distances = p.knn_query(d, k =50, end =50)
print labels, distances
```

**Comment by OElesin** [comment]
If you, please point me in the direction for this thanks

**Comment by yurymalkov** [comment]
@OElesin 
That would require significant coding. 
Simplest way to do it if you add all elements in a single batch of N elements.
To do that you can increase the Mmax0 parameter (it is possible to make it infinite size by having a separate array for each element), keep the timestamp (number of the elements) for each of the graph's connections, and make the elements' levels a decaying function.
After that you can extract the graph for any contiguous subset of N elements starting from zero element to M just by ignoring all links that have timestamp higher than M.
