### ISSUE TITLE
Issue while inserting/searching for a single vector

### ISSUE THREAD

**Issue by symisc** [nmslib/hnswlib#93]
Greeting,

I'm currently experimenting with HNSW and having a hard time figuring how to insert a single entry which is a numpy vector of dimension 512. Basically my computed vector have the following shape:

```
f1 = [-6.84065297e-02  2.42091250e-03 -3.57803353e-03  3.89208528e-03
 -2.28513479e-02  4.16927785e-02  2.04421561e-02  3.19429524e-02
 -3.44496779e-02  2.01440826e-02  7.60645140e-03  7.55775422e-02
 -6.46838024e-02  6.18326711e-03  4.17486131e-02  2.66419481e-02
 -4.48573716e-02  1.12289740e-02 -6.68355823e-02 -2.21468620e-02
... (512 entries)
]
```

My insertion code looks like the following:

```
index = hnswlib.Index(space = 'l2', dim = 512) 
index.init_index(max_elements = 100, ef_construction = 200, M = 16)

# Insert this single entry
index.add_items(f1, np.asarray([8512]))
```

My lookup code:

```
index.set_ef(50)
labels, distances = index.knn_query(f1, k = 4)
```

The following exception is thrown when searching: **_RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is to small_**

Any help is really appreciated! Thank you @searchivarius @yurymalkov for the awesome library!

**Comment by yurymalkov** [comment]
Hi @symisc,
The problem is that the search algorithm cannot find k=4 neighbors (there is only one element in the dataset), this triggers the exception which checks that the number of search results is exactly k (to return all the results in the contiguous array N*k). Probably, we need change this behavior in the future.

Summing up, if you add 3 new elements, the exception will disappear.

**Comment by symisc** [comment]
@yurymalkov  The issue reappear at random times when searching from multiple threads using the Python binding as attached in the screen capture here at https://i.imgur.com/IKMGKnF.png.

**Comment by yurymalkov** [comment]
@symisc Can you please provide a script that reproduces the error?

**Comment by symisc** [comment]
@yurymalkov  Sure, here is the Python gist that raise that error: https://gist.github.com/symisc/08492a2ff191f6e2bfb814371a4bb835

**Comment by yurymalkov** [comment]
@symisc Thanks! I'll look into it.

**Comment by yurymalkov** [comment]
@symisc I've finally looked through the code. Sorry, it took that long. The problem is that `knn_query` and `add_items` are not thread-safe with respect to each other.

**Comment by yinrong** [comment]
+1 should fix this
