### ISSUE TITLE
C++ example ? 

### ISSUE THREAD

**Issue by doofin** [nmslib/hnswlib#97]
Hi,I am new to C++ and I want to embed this into Scala app through JNA , but I can not find out how to use this as a C++ library. I saw the python bindings but can not understand the addPoint method:

```cpp
  appr_alg = new hnswlib::HierarchicalNSW<float>(l2space, maxElements, M, efConstruction, random_seed);
  int labeltype =1;
 float *vector_data=(float *) items.data(0);
  appr_alg->addPoint((void *) vector_data, labeltype);
```
specifically,Would you like to tell me why a single float value is feed instead of a  vector like std::vector<float>?

**Comment by searchivarius** [comment]
For Scala it's probably easier to just use a query server.

**Comment by yurymalkov** [comment]
Hi @doofin,

This is done to init the structure with the first element. 
After that you can add many points in parallel.

**Comment by searchivarius** [comment]
@doofin uhhh, sorry, disregard my comment. I confused repos.

**Comment by doofin** [comment]
thanks @yurymalkov and @searchivarius , I have made it to work but the accuracy is not ideal,the first returned vector is not the closest one,here is my bindings and invoked in Scala via JNA:

```cpp
#include "hnswalg.h"
#include "hnswlib.h"
#include <functional>
#include <iostream>
using namespace std;
hnswlib::HierarchicalNSW<float> *appr_alg;

extern "C" void knn(float x[], int size) {
  cout << "cur ct : " << appr_alg->cur_element_count << endl;
  vector<float> norm_array(x, x + sizeof x / sizeof x[0]);
  priority_queue<std::pair<float, hnswlib::labeltype>> result =
      appr_alg->searchKnn((void *)(&norm_array[0]), size);

  cout << "result : \n";
  cout << "size is " << result.size() << "\n";

  for (int i = 0; i <= result.size(); i++) {
    std::pair<float, hnswlib::labeltype> rr1 = result.top();
    cout << "res : " << result.top().second << endl;
    result.pop();
  }
}

extern "C" void addpt(float x[], int labeltype, int len) {
  vector<float> norm_array(x, x + sizeof x / sizeof x[0]);
  appr_alg->addPoint((void *)(&norm_array[0]), labeltype);
}

extern "C" int hnswInit(int dim) {
  hnswlib::SpaceInterface<float> *l2space;
  l2space = new hnswlib::L2Space(dim);
  appr_alg = new hnswlib::HierarchicalNSW<float>(l2space, 10000, 16, 100, 23);
  appr_alg->setEf(0);
  return 0;
};

```

```scala
object nmslib {
  trait nmsLib extends Library {
    def printt(): Int
    def hnswInit(dim: Int): Int
    def addpt(pt: Array[Float], label: Int, len: Int): Unit
    def knn(pt: Array[Float], len: Int): Unit
  }

  object nmsLib {
    def Instance = Native.loadLibrary("libmm.so", classOf[nmsLib])
  }
  def run(): Unit = {
    val inst = nmsLib.Instance
    nmsLib.Instance.printt()
    val dim = 3

    inst.hnswInit(dim)

    inst addpt (Array(1.2f, 20000f, 31f), 5, dim)
    inst addpt (Array(1.2f, 2f, 3.5f), 6, dim)
    inst addpt (Array(1.2f, 3f, 3.5f), 10, dim)

    inst.addpt(Array(1f, 2f, 3f), 3, dim)

    inst.knn(Array(1.1f, 2f, 3f), 4)
  }
}
```

and the result :

```
result : 
size is 4
res : 5
res : 10
res : 6

```
the vector of label 5 is always the first,albeit 6,10 and 3  is the closest,is this normal behavior?

**Comment by yurymalkov** [comment]
@doofin it seems ok, as ```result.top()``` returns the element starting from the furthest. 

Also:
1) in you code you do not need to convert anything to ```vector```.  You can directly pass float x[].
2) ```appr_alg->setEf(0);``` seems weird. Typically, ef is should be large (e.g. 100, 1000) to get high accuracy. In your case it is overridden with 4 inside the c++ lib (as ```k<=ef```).

**Comment by doofin** [comment]
@yurymalkov thanks! after adjusting setEf, it works quite well!
