### ISSUE TITLE
about getNeighborsByHeuristic2

### ISSUE THREAD

**Issue by ctero-graham** [nmslib/hnswlib#99]
@yurymalkov Would you please explain what does getNeighborsByHeuristic2 exactly do? Cannot quite follow that. 
Briefly, I think it is used to choose the nearest(by some means) elements from the set returned by searchBaseLayerST, however, why use the distance against the element at the top of the closest_queue for comparison?

**Comment by yurymalkov** [comment]
Hi @ctero-graham. Noe exactly sure what is the question. The heuristic is explained in the paper https://arxiv.org/abs/1603.09320 (Algorithm 4).

**Comment by wslfs** [comment]
@ctero-graham This alg does what  the paper described:
![image](https://user-images.githubusercontent.com/18738958/59583761-d58f0380-910e-11e9-8cf0-f516e6f15c76.png)
